services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    #volumes:
    #  - ./schema/clickhouse:/docker-entrypoint-initdb.d
    ports:
      - "8123"
      - "9000"
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8123/ping | grep -q 'Ok'" ]

  postgres:
    image: apache/age:release_PG16_1.6.0
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: imbi
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
