http:
  compress_response: true
  cookie_secret: imbi
  port: 8000
  processes: 2
  xheaders: true
ldap:
  enabled: true
  host: ldap
  port: 389
  ssl: false
  groups_dn: ou=groups,dc=example,dc=org
  users_dn: ou=users,dc=example,dc=org
  username: cn
  pool_size: 5
postgres:
  url: postgres://postgres@postgres:5432/postgres
session:
  redis_url: redis://redis:6379/0
stats:
  redis_url: redis://redis:6379/1
logging:
  version: 1
  formatters:
    verbose:
      format: "%(levelname) -10s %(asctime)s %(name) -15s %(funcName) -15s: %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: verbose
  loggers:
    imbi:
      level: INFO
      propagate: true
      handlers: [console]
    sprockets_postgres:
      level: WARNING
      propagate: true
      handlers: [console]
    tornado:
      level: INFO
      propagate: true
      handlers: [console]
  disable_existing_loggers: true
  incremental: false
