[mypy]
files = src/imbi_api
python_version = 3.14
namespace_packages = true
show_error_codes = true
strict = true
warn_unused_ignores = false

[mypy-aioboto3.*]
ignore_missing_imports = true

[mypy-botocore.*]
ignore_missing_imports = true

[mypy-fastapi.*]
ignore_missing_imports = true

[mypy-filetype.*]
ignore_missing_imports = true

[mypy-jsonpatch]
ignore_missing_imports = true
follow_imports = skip

[mypy-jsonpointer]
ignore_missing_imports = true
follow_imports = skip

[mypy-nanoid.*]
ignore_missing_imports = true

[mypy-qrcode.*]
ignore_missing_imports = true
