"""
Application Views

"""
from tornado import web

from . import (
    configuration_systems,
    cookie_cutters,
    data_centers,
    deployment_types,
    environments,
    groups,
    namespaces,
    openapi,
    operations,
    orchestration_systems,
    projects,
    project_dependencies,
    project_fact_type_options,
    project_fact_types,
    project_link_types,
    project_links,
    project_types,
    settings,
    status,
    ui
)

URLS = [
           web.url(r'^/$', ui.IndexRequestHandler),
           web.url(r'^/api-docs/$', openapi.RequestHandler),
           web.url(r'^/api-docs/(openapi.yaml)$', openapi.RequestHandler),
           web.url(r'^/configuration_systems$',
                   configuration_systems.AdminCRUDRequestHandler),
           web.url(r'^/configuration_systems/(?P<name>[\w_\-%\+]+)$',
                   configuration_systems.AdminCRUDRequestHandler,
                   name='configuration-systems'),
           web.url(r'^/cookie_cutters', cookie_cutters.AdminCRUDRequestHandler),
           web.url(r'^/cookie_cutters/(?P<name>[\w_\-%\+]+)$',
                   cookie_cutters.AdminCRUDRequestHandler,
                   name='cookie-cutters'),
           web.url(r'^/deployment_types$',
                   deployment_types.AdminCRUDRequestHandler),
           web.url(r'^/deployment_types/(?P<name>[\w_\-%\+]+$)',
                   deployment_types.AdminCRUDRequestHandler,
                   name='deployment-types'),
           web.url(r'^/data_centers$', data_centers.AdminCRUDRequestHandler),
           web.url(r'^/data_centers/(?P<name>[\w_\-%\+]+)$',
                   data_centers.AdminCRUDRequestHandler,
                   name='data-centers'),
           web.url(r'^/environments$', environments.AdminCRUDRequestHandler),
           web.url(r'^/environments/(?P<name>[\w_\-%\+]+)$',
                   environments.AdminCRUDRequestHandler,
                   name='environments'),
           web.url(r'^/groups$', groups.AdminCRUDRequestHandler),
           web.url(r'^/groups/(?P<name>[\w_\-%\+]+)$',
                   groups.AdminCRUDRequestHandler,
                   name='groups'),
           web.url(r'^/namespaces$', namespaces.AdminCRUDRequestHandler),
           web.url(r'^/namespaces/(?P<id>\d+)$',
                   namespaces.AdminCRUDRequestHandler,
                   name='namespaces'),
           web.url(r'^/orchestration_systems$',
                   orchestration_systems.AdminCRUDRequestHandler),
           web.url(r'^/orchestration_systems/(?P<name>[\w_\-%\+]+)$',
                   orchestration_systems.AdminCRUDRequestHandler,
                   name='orchestration-systems'),
           web.url(r'^/project_fact_types$',
                   project_fact_types.AdminCRUDRequestHandler),
           web.url(r'^/project_fact_types/(?P<id>\d+)$',
                   project_fact_types.AdminCRUDRequestHandler,
                   name='project-fact-types'),
           web.url(r'^/project_fact_type_options$',
                   project_fact_type_options.AdminCRUDRequestHandler),
           web.url(r'^/project_fact_type_options/(?P<id>\d+)$',
                   project_fact_type_options.AdminCRUDRequestHandler,
                   name='project-fact-type-options'),
           web.url(r'^/project_link_types$',
                   project_link_types.AdminCRUDRequestHandler),
           web.url(r'^/project_link_types/(?P<id>\d+)$',
                   project_link_types.AdminCRUDRequestHandler,
                   name='project-link-types'),
           web.url(r'^/project_types$', project_types.AdminCRUDRequestHandler),
           web.url(r'^/project_types/(?P<id>\d+)$',
                   project_types.AdminCRUDRequestHandler,
                   name='project-types'),
           web.url(r'^/projects$', projects.CollectionRequestHandler,
                   name='projects'),
           web.url(r'^/projects/(?P<id>\d+)$', projects.RecordRequestHandler,
                   name='project'),
           web.url(r'^/projects/(?P<project_id>\d+)/dependencies$',
                   project_dependencies.CollectionRequestHandler,
                   name='project-dependencies'),
           web.url(r'^/projects/(?P<project_id>\d+)/dependencies/'
                   r'(?P<dependency_id>\d+)$',
                   project_dependencies.RecordRequestHandler,
                   name='project-dependency'),
           web.url(r'^/projects/(?P<project_id>\d+)/links$',
                   project_links.CollectionRequestHandler,
                   name='project-links'),
           web.url(r'^/projects/(?P<project_id>\d+)/links/'
                   r'(?P<link_type_id>\d+)$',
                   project_links.RecordRequestHandler,
                   name='project-link'),
           web.url(r'^/status$', status.RequestHandler),
           web.url(r'^/ui/groups$', ui.GroupsRequestHandler),
           web.url(r'^/ui/login$', ui.LoginRequestHandler),
           web.url(r'^/ui/logout$', ui.LogoutRequestHandler),
           web.url(r'^/ui/user$', ui.UserRequestHandler),
           web.url(r'^/ui/.*$', ui.IndexRequestHandler)
       ] + operations.URLS + settings.URLS
