title: Configuration System
description: Configuration Management or Storage System
type: object
properties:
  name:
    description: The display name for a configuration system
    type: string
  description:
    description: A description of the configuration system
    type: string
    nullable: true
  icon_class:
    description: Font Awesome UI icon class
    type: string
required:
  - name
  - icon_class
additionalProperties: false
