title: Project
description: Describes a project managed by Imbi
type: object
properties:
  namespace:
    description: The project namespace
    type: string
  name:
    description: The project name
    type: string
  slug:
    description: The project URL slug (In GitLab and other projects)
    type: string
  description:
    description: Long for description of the project
    type: string
    nullable: true
  project_type:
    description: The project type (API, Consumer, Database, etc)
    type: string
  environments:
    description: The operational environments the project is available in
    type: array
    items:
      type: string
    minLength: 1
    nullable: true
  data_center:
    description: The data center the project runs in
    type: string
    nullable: true
  configuration_system:
    description: The system used to configure the project (Ansible, Consul, etc)
    type: string
    nullable: true
  deployment_type:
    description: How the project is deployed (Jenkins, GitLab-CI, etc)
    type: string
    nullable: true
  orchestration_system:
    description: TThe system used to manage the runtime state of the project (Kubernetes, Nomad, etc)
    type: string
    nullable: true
required:
  - namespace
  - name
  - slug
  - project_type
additionalProperties: false
