-- The statements that a second deploy prints. root:schema-check
-- compares the second deploy with this file, without comment lines and
-- blank lines, line by line.
--
-- With the pinned pglifecycle commit, the second deploy is empty, so
-- this file has no statements. When a pglifecycle defect makes a
-- statement repeat on each deploy, add it here, and add the defect to
-- README "Known problems".
