openapi: 3.0.3

info:
  title: Imbi
  description: |-
    Imbi is an operational management platform for medium to large environments.
  license:
    name: BSD 3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  version: '{{ settings["version"] }}'
  contact:
    name: AWeber
    url: https://github.com/aweber/imbi
  x-logo:
    url: /static/images/logo.png

components:
  securitySchemes:
    session:
      type: apiKey
      description: Uses the session cookie of an authenticated user to authenticate each API request
      in: cookie
      name: session
    token:
      type: apiKey
      description: Uses an API key generated for a user to authenticate each API request
      in: header
      name: Private-Token

security:
  - session: []
  - token: []

paths:
  /configuration-systems:
    { $ref: 'endpoints/configuration_system.yaml#/paths/collection' }
  /configuration-systems/{name}:
    { $ref: 'endpoints/configuration_system.yaml#/paths/manage' }
  /cookie-cutters: { $ref: 'endpoints/cookie_cutter.yaml#/paths/collection' }
  /cookie-cutters/{name}: { $ref: 'endpoints/cookie_cutter.yaml#/paths/manage' }
  /data-centers: { $ref: 'endpoints/data_center.yaml#/paths/collection' }
  /data-centers/{name}: { $ref: 'endpoints/data_center.yaml#/paths/manage' }
  /deployment-types:
    { $ref: 'endpoints/deployment_type.yaml#/paths/collection' }
  /deployment-types/{name}:
    { $ref: 'endpoints/deployment_type.yaml#/paths/manage' }
  /environments: { $ref: 'endpoints/environment.yaml#/paths/collection' }
  /environments/{name}: { $ref: 'endpoints/environment.yaml#/paths/manage' }
  /groups: { $ref: 'endpoints/group.yaml#/paths/collection' }
  /groups/{name}: { $ref: 'endpoints/group.yaml#/paths/manage' }
  /namespaces: { $ref: 'endpoints/namespace.yaml#/paths/collection' }
  /namespaces/{id}: { $ref: 'endpoints/namespace.yaml#/paths/manage' }
  /orchestration-systems:
    { $ref: 'endpoints/orchestration_system.yaml#/paths/collection' }
  /orchestration-systems/{name}:
    { $ref: 'endpoints/orchestration_system.yaml#/paths/manage' }
  /permissions: { $ref: 'endpoints/permissions.yaml#/paths/collection' }
  /project-fact-types:
    { $ref: 'endpoints/project_fact_type.yaml#/paths/collection' }
  /project-fact-types/{fact_type_id}:
    { $ref: 'endpoints/project_fact_type.yaml#/paths/manage' }
  /project-fact-type-options:
    { $ref: 'endpoints/project_fact_type_option.yaml#/paths/collection' }
  /project-fact-type-options/{id}:
    { $ref: 'endpoints/project_fact_type_option.yaml#/paths/manage' }
  /project-link-types:
    { $ref: 'endpoints/project_link_type.yaml#/paths/collection' }
  /project-link-types/{id}:
    { $ref: 'endpoints/project_link_type.yaml#/paths/manage' }
  /project-types: { $ref: 'endpoints/project_type.yaml#/paths/collection' }
  /project-types/{id}: { $ref: 'endpoints/project_type.yaml#/paths/manage' }
  /projects: { '$ref': 'endpoints/projects.yaml#/paths/collection' }
  /projects/{id}: { '$ref': 'endpoints/project.yaml#/paths/manage' }
  /projects/{id}/links: { '$ref': 'endpoints/links.yaml#/paths/collection' }
  /projects/{id}/links/{link_type_id}:
    { '$ref': 'endpoints/link.yaml#/paths/manage' }
  /projects/{id}/dependencies:
    { '$ref': 'endpoints/dependencies.yaml#/paths/collection' }
  /projects/{id}/dependencies/{dependency_id}:
    { '$ref': 'endpoints/dependency.yaml#/paths/manage' }
  /status: { $ref: 'status.yaml#/paths/status' }

tags:
  - { '$ref': 'endpoints/configuration_system.yaml#/tag' }
  - { '$ref': 'endpoints/cookie_cutter.yaml#/tag' }
  - { '$ref': 'endpoints/data_center.yaml#/tag' }
  - { '$ref': 'endpoints/deployment_type.yaml#/tag' }
  - { '$ref': 'endpoints/environment.yaml#/tag' }
  - { '$ref': 'endpoints/group.yaml#/tag' }
  - { '$ref': 'endpoints/namespace.yaml#/tag' }
  - { '$ref': 'endpoints/orchestration_system.yaml#/tag' }
  - { '$ref': 'endpoints/project_fact_type.yaml#/tag' }
  - { '$ref': 'endpoints/project_fact_type_option.yaml#/tag' }
  - { '$ref': 'endpoints/project_link_type.yaml#/tag' }
  - { '$ref': 'endpoints/project_type.yaml#/tag' }
  - name: Projects
    description: Endpoints used for the management of projects
  - name: Settings
    description: Endpoints used for retrieving settings for the Imbi UI
  - { '$ref': 'status.yaml#/tag' }

x-tagGroups:
  - name: Metadata
    tags:
      - Configuration Systems
      - Cookie Cutters
      - Data Centers
      - Deployment Types
      - Environments
      - Groups
      - Orchestration Systems
      - Project Fact Types
      - Project Fact Type Options
      - Project Link Types
      - Project Types
      - Teams
  - name: Project Management
    tags:
      - Projects
  - name: Settings
    tags:
      - Settings
  - name: Other
    tags:
      - Health Check
