openapi: 3.0.3

info:
  title: Imbi
  description: |-
    Imbi is an operational management platform for medium to large environments.
  license:
    name: BSD 3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  version: '{{ settings["version"] }}'
  contact:
    name: AWeber
    url: https://github.com/aweber/imbi
  x-logo:
    url: /static/images/logo.png

components:
  securitySchemes:
    session:
      type: apiKey
      description: Uses the session cookie of an authenticated user to authenticate each API request
      in: cookie
      name: session
    token:
      type: apiKey
      description: Uses an API key generated for a user to authenticate each API request
      in: header
      name: Private-Token

security:
  - session: []
  - token: []

paths:
  /admin/configuration_system:
    { $ref: 'admin/configuration_system.yaml#/paths/create' }
  /admin/configuration_system/{name}:
    { $ref: 'admin/configuration_system.yaml#/paths/manage' }
  /admin/cookie_cutter: { $ref: 'admin/cookie_cutter.yaml#/paths/create' }
  /admin/cookie_cutter/{name}:
    { $ref: 'admin/cookie_cutter.yaml#/paths/manage' }
  /admin/data_center: { $ref: 'admin/data_center.yaml#/paths/create' }
  /admin/data_center/{name}: { $ref: 'admin/data_center.yaml#/paths/manage' }
  /admin/deployment_type: { $ref: 'admin/deployment_type.yaml#/paths/create' }
  /admin/deployment_type/{name}:
    { $ref: 'admin/deployment_type.yaml#/paths/manage' }
  /admin/environment: { $ref: 'admin/environment.yaml#/paths/create' }
  /admin/environment/{name}: { $ref: 'admin/environment.yaml#/paths/manage' }
  /admin/group: { $ref: 'admin/group.yaml#/paths/create' }
  /admin/group/{name}: { $ref: 'admin/group.yaml#/paths/manage' }
  /admin/namespace: { $ref: 'admin/namespace.yaml#/paths/create' }
  /admin/namespace/{namespace}: { $ref: 'admin/namespace.yaml#/paths/manage' }
  /admin/orchestration_system:
    { $ref: 'admin/orchestration_system.yaml#/paths/create' }
  /admin/orchestration_system/{name}:
    { $ref: 'admin/orchestration_system.yaml#/paths/manage' }
  /admin/project_fact_type:
    { $ref: 'admin/project_fact_type.yaml#/paths/create' }
  /admin/project_fact_type/{project_type}/{fact_type}:
    { $ref: 'admin/project_fact_type.yaml#/paths/manage' }
  /admin/project_fact_type_option:
    { $ref: 'admin/project_fact_type_option.yaml#/paths/create' }
  /admin/project_fact_type_option/{project_type}/{fact_type}/{value}:
    { $ref: 'admin/project_fact_type_option.yaml#/paths/manage' }
  /admin/project_link_type:
    { $ref: 'admin/project_link_type.yaml#/paths/create' }
  /admin/project_link_type/{link_type}:
    { $ref: 'admin/project_link_type.yaml#/paths/manage' }
  /admin/project_type: { $ref: 'admin/project_type.yaml#/paths/create' }
  /admin/project_type/{name}: { $ref: 'admin/project_type.yaml#/paths/manage' }

  /projects: { '$ref': 'project/projects.yaml#/paths/collection' }
  /projects/{namespace}/{name}: { '$ref': 'project/project.yaml#/paths/manage' }
  /projects/{namespace}/{name}/links:
    { '$ref': 'project/links.yaml#/paths/collection' }
  /projects/{namespace}/{name}/links/{link_type}:
    { '$ref': 'project/link.yaml#/paths/manage' }
  /projects/{namespace}/{name}/dependencies:
    { '$ref': 'project/dependencies.yaml#/paths/collection' }
  ? /projects/{namespace}/{name}/dependencies/{dependency_namespace}/{dependency_name}
  : { '$ref': 'project/dependency.yaml#/paths/manage' }

  /settings/configuration_systems:
    { $ref: 'settings/configuration_systems.yaml#/paths/collection' }
  /settings/cookie_cutters:
    { $ref: 'settings/cookie_cutters.yaml#/paths/collection' }
  /settings/data_centers:
    { $ref: 'settings/data_centers.yaml#/paths/collection' }
  /settings/deployment_types:
    { $ref: 'settings/deployment_types.yaml#/paths/collection' }
  /settings/environments:
    { $ref: 'settings/environments.yaml#/paths/collection' }
  /settings/groups: { $ref: 'settings/groups.yaml#/paths/collection' }
  /settings/namespaces: { $ref: 'settings/namespaces.yaml#/paths/collection' }
  /settings/orchestration_systems:
    { $ref: 'settings/orchestration_systems.yaml#/paths/collection' }
  /settings/permissions: { $ref: 'settings/permissions.yaml#/paths/collection' }
  /settings/project_fact_type_options:
    { $ref: 'settings/project_fact_type_options.yaml#/paths/collection' }
  /settings/project_fact_types:
    { $ref: 'settings/project_fact_types.yaml#/paths/collection' }
  /settings/project_link_types:
    { $ref: 'settings/project_link_types.yaml#/paths/collection' }
  /settings/project_types:
    { $ref: 'settings/project_types.yaml#/paths/collection' }

  /status: { $ref: 'status.yaml#/paths/status' }

tags:
  - { '$ref': 'admin/configuration_system.yaml#/tag' }
  - { '$ref': 'admin/cookie_cutter.yaml#/tag' }
  - { '$ref': 'admin/data_center.yaml#/tag' }
  - { '$ref': 'admin/deployment_type.yaml#/tag' }
  - { '$ref': 'admin/environment.yaml#/tag' }
  - { '$ref': 'admin/group.yaml#/tag' }
  - { '$ref': 'admin/namespace.yaml#/tag' }
  - { '$ref': 'admin/orchestration_system.yaml#/tag' }
  - { '$ref': 'admin/project_fact_type.yaml#/tag' }
  - { '$ref': 'admin/project_fact_type_option.yaml#/tag' }
  - { '$ref': 'admin/project_link_type.yaml#/tag' }
  - { '$ref': 'admin/project_type.yaml#/tag' }
  - name: Projects
    description: Endpoints used for the management of projects
  - name: Settings
    description: Endpoints used for retrieving settings for the Imbi UI
  - { '$ref': 'status.yaml#/tag' }

x-tagGroups:
  - name: Administration
    tags:
      - Configuration Systems
      - Cookie Cutters
      - Data Centers
      - Deployment Types
      - Environments
      - Groups
      - Orchestration Systems
      - Project Fact Types
      - Project Fact Type Options
      - Project Link Types
      - Project Types
      - Teams
  - name: Project Management
    tags:
      - Projects
  - name: Settings
    tags:
      - Settings
  - name: Other
    tags:
      - Health Check
