openapi: 3.0.3

info:
  title: Imbi
  description: |-
    Imbi is an operational management platform for medium to large environments.
  license:
    name: BSD 3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  version: '{{ settings["version"] }}'
  contact:
    name: AWeber
    url: https://github.com/aweber/imbi
  x-logo:
    url: /static/images/logo.png

components:
  securitySchemes:
    session:
      type: apiKey
      description: Uses the session cookie of an authenticated user to authenticate each API request
      in: cookie
      name: session
    token:
      type: apiKey
      description: Uses an API key generated for a user to authenticate each API request
      in: header
      name: Private-Token

security:
  - session: []
  - token: []

paths:
  /configuration_systems:
    { $ref: 'endpoints/configuration_system.yaml#/paths/create' }
  /configuration_systems/{name}:
    { $ref: 'endpoints/configuration_system.yaml#/paths/manage' }
  /cookie_cutters: { $ref: 'endpoints/cookie_cutter.yaml#/paths/create' }
  /cookie_cutters/{name}: { $ref: 'endpoints/cookie_cutter.yaml#/paths/manage' }
  /data_centers: { $ref: 'endpoints/data_center.yaml#/paths/create' }
  /data_centers/{name}: { $ref: 'endpoints/data_center.yaml#/paths/manage' }
  /deployment_types: { $ref: 'endpoints/deployment_type.yaml#/paths/create' }
  /deployment_types/{name}:
    { $ref: 'endpoints/deployment_type.yaml#/paths/manage' }
  /environments: { $ref: 'endpoints/environment.yaml#/paths/create' }
  /environments/{name}: { $ref: 'endpoints/environment.yaml#/paths/manage' }
  /groups: { $ref: 'endpoints/group.yaml#/paths/create' }
  /groups/{name}: { $ref: 'endpoints/group.yaml#/paths/manage' }
  /namespaces: { $ref: 'endpoints/namespace.yaml#/paths/create' }
  /namespaces/{id}: { $ref: 'endpoints/namespace.yaml#/paths/manage' }
  /orchestration_systems:
    { $ref: 'endpoints/orchestration_system.yaml#/paths/create' }
  /orchestration_systems/{name}:
    { $ref: 'endpoints/orchestration_system.yaml#/paths/manage' }
  /project_fact_types:
    { $ref: 'endpoints/project_fact_type.yaml#/paths/create' }
  /project_fact_types/{fact_type_id}:
    { $ref: 'endpoints/project_fact_type.yaml#/paths/manage' }
  /project_fact_type_options:
    { $ref: 'endpoints/project_fact_type_option.yaml#/paths/create' }
  /project_fact_type_options/{id}:
    { $ref: 'endpoints/project_fact_type_option.yaml#/paths/manage' }
  /project_link_types:
    { $ref: 'endpoints/project_link_type.yaml#/paths/create' }
  /project_link_types/{id}:
    { $ref: 'endpoints/project_link_type.yaml#/paths/manage' }
  /project_types: { $ref: 'endpoints/project_type.yaml#/paths/create' }
  /project_types/{id}: { $ref: 'endpoints/project_type.yaml#/paths/manage' }

  /projects: { '$ref': 'project/projects.yaml#/paths/collection' }
  /projects/{id}: { '$ref': 'project/project.yaml#/paths/manage' }
  /projects/{id}/links: { '$ref': 'project/links.yaml#/paths/collection' }
  /projects/{id}/links/{link_type_id}:
    { '$ref': 'project/link.yaml#/paths/manage' }
  /projects/{id}/dependencies:
    { '$ref': 'project/dependencies.yaml#/paths/collection' }
  /projects/{id}/dependencies/{dependency_id}:
    { '$ref': 'project/dependency.yaml#/paths/manage' }

  /settings/configuration_systems:
    { $ref: 'settings/configuration_systems.yaml#/paths/collection' }
  /settings/cookie_cutters:
    { $ref: 'settings/cookie_cutters.yaml#/paths/collection' }
  /settings/data_centers:
    { $ref: 'settings/data_centers.yaml#/paths/collection' }
  /settings/deployment_types:
    { $ref: 'settings/deployment_types.yaml#/paths/collection' }
  /settings/environments:
    { $ref: 'settings/environments.yaml#/paths/collection' }
  /settings/groups: { $ref: 'settings/groups.yaml#/paths/collection' }
  /settings/namespaces: { $ref: 'settings/namespaces.yaml#/paths/collection' }
  /settings/orchestration_systems:
    { $ref: 'settings/orchestration_systems.yaml#/paths/collection' }
  /settings/permissions: { $ref: 'settings/permissions.yaml#/paths/collection' }
  /settings/project_fact_type_options:
    { $ref: 'settings/project_fact_type_options.yaml#/paths/collection' }
  /settings/project_fact_types:
    { $ref: 'settings/project_fact_types.yaml#/paths/collection' }
  /settings/project_link_types:
    { $ref: 'settings/project_link_types.yaml#/paths/collection' }
  /settings/project_types:
    { $ref: 'settings/project_types.yaml#/paths/collection' }

  /status: { $ref: 'status.yaml#/paths/status' }

tags:
  - { '$ref': 'endpoints/configuration_system.yaml#/tag' }
  - { '$ref': 'endpoints/cookie_cutter.yaml#/tag' }
  - { '$ref': 'endpoints/data_center.yaml#/tag' }
  - { '$ref': 'endpoints/deployment_type.yaml#/tag' }
  - { '$ref': 'endpoints/environment.yaml#/tag' }
  - { '$ref': 'endpoints/group.yaml#/tag' }
  - { '$ref': 'endpoints/namespace.yaml#/tag' }
  - { '$ref': 'endpoints/orchestration_system.yaml#/tag' }
  - { '$ref': 'endpoints/project_fact_type.yaml#/tag' }
  - { '$ref': 'endpoints/project_fact_type_option.yaml#/tag' }
  - { '$ref': 'endpoints/project_link_type.yaml#/tag' }
  - { '$ref': 'endpoints/project_type.yaml#/tag' }
  - name: Projects
    description: Endpoints used for the management of projects
  - name: Settings
    description: Endpoints used for retrieving settings for the Imbi UI
  - { '$ref': 'status.yaml#/tag' }

x-tagGroups:
  - name: Administration
    tags:
      - Configuration Systems
      - Cookie Cutters
      - Data Centers
      - Deployment Types
      - Environments
      - Groups
      - Orchestration Systems
      - Project Fact Types
      - Project Fact Type Options
      - Project Link Types
      - Project Types
      - Teams
  - name: Project Management
    tags:
      - Projects
  - name: Settings
    tags:
      - Settings
  - name: Other
    tags:
      - Health Check
