openapi: 3.0.3

info:
  title: Imbi
  description: |-
    Imbi is an operational management platform for medium to large environments.
  license:
    name: BSD 3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  version: '{{ settings["version"] }}'
  contact:
    name: AWeber
    url: https://github.com/aweber/imbi
  x-logo:
    url: /static/images/logo.png

components:
  securitySchemes:
    session:
      type: apiKey
      description: Uses the session cookie of an authenticated user to authenticate each API request
      in: cookie
      name: session
    token:
      type: apiKey
      description: Uses an API key generated for a user to authenticate each API request
      in: header
      name: Private-Token

security:
  - session: []
  - token: []

paths:
  /authentication-tokens:
    { $ref: 'endpoints/authentication_tokens.yaml#/paths/collection' }
  /authentication-tokens/{token}:
    { $ref: 'endpoints/authentication_tokens.yaml#/paths/manage' }
  /cookie-cutters: { $ref: 'endpoints/cookie_cutter.yaml#/paths/collection' }
  /cookie-cutters/{name}: { $ref: 'endpoints/cookie_cutter.yaml#/paths/manage' }
  /environments: { $ref: 'endpoints/environment.yaml#/paths/collection' }
  /environments/{name}: { $ref: 'endpoints/environment.yaml#/paths/manage' }
  /groups: { $ref: 'endpoints/group.yaml#/paths/collection' }
  /groups/{name}: { $ref: 'endpoints/group.yaml#/paths/manage' }
  /namespaces: { $ref: 'endpoints/namespace.yaml#/paths/collection' }
  /namespaces/{id}: { $ref: 'endpoints/namespace.yaml#/paths/manage' }
  /operations-log: { '$ref': 'endpoints/operations_log.yaml#/paths/collection' }
  /operations-log/{id}: { '$ref': 'endpoints/operations_log.yaml#/paths/manage' }
  /permissions: { $ref: 'endpoints/permissions.yaml#/paths/collection' }
  /project-fact-types:
    { $ref: 'endpoints/project_fact_type.yaml#/paths/collection' }
  /project-fact-types/{fact_type_id}:
    { $ref: 'endpoints/project_fact_type.yaml#/paths/manage' }
  /project-fact-type-enums:
    { $ref: 'endpoints/project_fact_type_enum.yaml#/paths/collection' }
  /project-fact-type-enums/{id}:
    { $ref: 'endpoints/project_fact_type_enum.yaml#/paths/manage' }
  /project-fact-type-ranges:
    { $ref: 'endpoints/project_fact_type_range.yaml#/paths/collection' }
  /project-fact-type-ranges/{id}:
    { $ref: 'endpoints/project_fact_type_range.yaml#/paths/manage' }
  /project-link-types:
    { $ref: 'endpoints/project_link_type.yaml#/paths/collection' }
  /project-link-types/{id}:
    { $ref: 'endpoints/project_link_type.yaml#/paths/manage' }
  /project-types: { $ref: 'endpoints/project_type.yaml#/paths/collection' }
  /project-types/{id}: { $ref: 'endpoints/project_type.yaml#/paths/manage' }
  /projects: { '$ref': 'endpoints/projects.yaml#/paths/collection' }
  /projects/{id}: { '$ref': 'endpoints/projects.yaml#/paths/manage' }
  /projects/{id}/facts:
    { '$ref': 'endpoints/project_facts.yaml#/paths/collection' }
  /projects/{id}/fact-types:
    { '$ref': 'endpoints/project_fact_types.yaml#/paths/collection' }
  /projects/{id}/feed:
    { '$ref': 'endpoints/project_activity_feed.yaml#/paths/collection' }
  /projects/{id}/links:
    { '$ref': 'endpoints/project_links.yaml#/paths/collection' }
  /projects/{id}/links/{link_type_id}:
    { '$ref': 'endpoints/project_links.yaml#/paths/manage' }
  /projects/{id}/dependencies:
    { '$ref': 'endpoints/project_dependencies.yaml#/paths/collection' }
  /projects/{id}/dependencies/{dependency_id}:
    { '$ref': 'endpoints/project_dependencies.yaml#/paths/manage' }
  /projects/{id}/urls:
    { '$ref': 'endpoints/project_urls.yaml#/paths/collection' }
  /projects/{id}/urls/{environment}:
    { '$ref': 'endpoints/project_urls.yaml#/paths/manage' }
  /status: { $ref: 'status.yaml#/paths/status' }

tags:
  - name: Cookie Cutters
    description: Endpoints used for the management of project creation cookie cutters
  - name: Environments
    description: Endpoints used for the management different target environments for projects to run in.
  - name: Groups
    description: |-
      Endpoints used to manage the groups that Imbi users are able to be members of.
  - name: Namespaces
    description: Endpoints used for the management of organizational namespaces
  - name: Fact Types
    description: |-
      Management of records that define types facts that may be collected for a project.

      Project facts may be used to calculate a current project health score. For more
      information on project health score, see the compliance documentation.
    x-displayName: Project Fact Types
  - name: Fact Type Enums
    description: |-
      Management of records that define enum values for different fact types that may be collected for a project.

      Project facts enums provide the possible values for project facts, and are
      used to compute the score of that project fact. For more information on
      project health score, see the compliance documentation.
    x-displayName: Project Fact Type Enums
  - name: Fact Type Ranges
    description: |-
      Management of records that define range values for different fact types that
      may be collected for a project.

      Project facts ranges provide the possible range values for project facts, and
      are used to compute the score of that project fact. For more information on
      project health score, see the compliance documentation.
    x-displayName: Project Fact Type Ranges
  - name: Project Link Types
    description: |-
      Management of records that define types of links or URLs to associate with a project
  - name: Project Types
    description: Endpoints used for the management different types of projects managed in Imbi (APIs, Databases, etc)
  - name: Projects
    description: Endpoints used for the management of projects
  - name: Project Activity Feed
    description: Endpoints that detail activity on a project
  - name: Project Dependencies
    description: Endpoints used to manage the relationships of projects to other projects
  - name: Project Facts
    description: Endpoints for managing the current facts describing the project
  - name: Project Fact Types
    description: An endpoint for returning the project fact types for a specific project
  - name: Project Links
    description: Endpoints used to manage links to external resources for a project
  - name: Project URLs
    description: Endpoints used to manage urls to the project in each operational environment
  - name: Operations Log
    description: Endpoints used for created, querying, and managing entries in the Operations Log
  - name: Settings
    description: Endpoints used for retrieving settings for the Imbi UI
  - name: Health Check / Status
    description: |-
      The health check endpoint can be used by a load balancer to indicate
      service health.

x-tagGroups:
  - name: Administration
    tags:
      - Groups
      - Users
  - name: Metadata
    tags:
      - Cookie Cutters
      - Environments
      - Namespaces
      - Fact Types
      - Fact Type Enums
      - Fact Type Ranges
      - Project Link Types
      - Project Types
  - name: Operations Log
    tags:
      - Operations Log
  - name: Project Management
    tags:
      - Projects
      - Project Activity Feed
      - Project Dependencies
      - Project Facts
      - Project Fact Types
      - Project Links
      - Project URLs
  - name: Current User
    tags:
      - User
  - name: UI Specific
    tags:
      - Dashboard
      - Settings
  - name: Other
    tags:
      - Health Check / Status
