export {default as Admin} from "./Admin"
export {Dashboard} from "./Dashboard"
export {default as Error} from "./Error"
export {Loading} from "./Loading"
export {default as Login} from "./Login"
export {default as Main} from "./Main"
export {NotFound} from "./NotFound"
export {default as User} from "./User"
