export {Admin} from "./Admin"
export {Dashboard} from "./Dashboard"
export {Loading} from "./Loading"
export {default as Login} from "./Login"
export {default as Main} from "./Main"
export {default as NotFound} from "./NotFound"
export {default as User} from "./User"
