"""The schema rules of ``schemata/``. Generated; do not edit.

Regenerate with
``python libraries/common/tests/test_etl_audit_schema.py --write``.
"""

# ruff: noqa: E501

from imbi.common.db.etl.audit.schema import (
    Check,
    Column,
    Domain,
    ForeignKey,
    Table,
    Unique,
)

# fmt: off
DOMAINS: dict[str, Domain] = {
    'public.jsonb_array': Domain(
        'public.jsonb_array', 'JSONB',
        checks=(
            Check('jsonb_array_check', "(jsonb_typeof(VALUE) = 'array'::text)"),
        ),
    ),
    'public.jsonb_object': Domain(
        'public.jsonb_object', 'JSONB',
        checks=(
            Check('jsonb_object_check', "(jsonb_typeof(VALUE) = 'object'::text)"),
        ),
    ),
    'public.slug': Domain(
        'public.slug', 'TEXT',
        checks=(
            Check('slug_check', "(VALUE ~ '^[a-z0-9]+(-[a-z0-9]+)*$'::text)"),
        ),
    ),
}

TABLES: dict[str, Table] = {
    'advisories': Table(
        'advisories',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('cve_id', 'TEXT', False, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
        ),
        checks=(
            Check('cve_id_upper', '(cve_id = upper(cve_id))'),
        ),
        uniques=(
            Unique('advisories_pkey', ('id',), None, False),
            Unique('advisories_cve_id_key', ('cve_id',), None, False),
        ),
    ),
    'ai_model_teams': Table(
        'ai_model_teams',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('ai_model_id', 'TEXT', False, False),
            Column('team_id', 'TEXT', False, False),
        ),
        uniques=(
            Unique('ai_model_teams_pkey', ('ai_model_id', 'team_id'), None, False),
        ),
        foreign_keys=(
            ForeignKey('ai_model_teams_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('ai_model_teams_ai_model_id_fkey', ('organization_id', 'ai_model_id'), 'ai_models', ('organization_id', 'id')),
            ForeignKey('ai_model_teams_team_id_fkey', ('organization_id', 'team_id'), 'teams', ('organization_id', 'id')),
        ),
    ),
    'ai_models': Table(
        'ai_models',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('name', 'TEXT', False, False),
            Column('slug', 'public.slug', False, False),
            Column('description', 'TEXT', True, False),
            Column('icon', 'TEXT', True, False),
            Column('provider_id', 'TEXT', False, False),
            Column('provider_model_id', 'TEXT', False, False),
            Column('kind', 'TEXT', False, True),
            Column('enabled', 'BOOLEAN', False, True),
            Column('access_scope', 'TEXT', False, True),
            Column('context_window', 'INTEGER', True, False),
            Column('max_output_tokens', 'INTEGER', True, False),
            Column('input_cost_per_million', 'NUMERIC(12,6)', True, False),
            Column('output_cost_per_million', 'NUMERIC(12,6)', True, False),
            Column('default_temperature', 'NUMERIC(4,3)', True, False),
            Column('default_top_p', 'NUMERIC(4,3)', True, False),
            Column('monthly_spend_cap', 'NUMERIC(12,2)', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('kind_valid', "(kind = ANY (ARRAY['chat'::text, 'completion'::text]))"),
            Check('access_scope_valid', "(access_scope = ANY (ARRAY['organization'::text, 'restricted'::text]))"),
            Check('context_window_positive', '(context_window > 0)'),
            Check('max_output_tokens_positive', '(max_output_tokens > 0)'),
            Check('input_cost_positive', '(input_cost_per_million >= (0)::numeric)'),
            Check('output_cost_positive', '(output_cost_per_million >= (0)::numeric)'),
            Check('temperature_range', '((default_temperature >= (0)::numeric) AND (default_temperature <= (2)::numeric))'),
            Check('top_p_range', '((default_top_p >= (0)::numeric) AND (default_top_p <= (1)::numeric))'),
            Check('spend_cap_positive', '(monthly_spend_cap >= (0)::numeric)'),
        ),
        uniques=(
            Unique('ai_models_pkey', ('id',), None, False),
            Unique('ai_models_organization_id_id_key', ('organization_id', 'id'), None, False),
            Unique('ai_models_organization_id_slug_key', ('organization_id', 'slug'), None, False),
            Unique('ai_models_provider_id_provider_model_id_key', ('provider_id', 'provider_model_id'), None, False),
        ),
        foreign_keys=(
            ForeignKey('ai_models_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('ai_models_provider_id_fkey', ('organization_id', 'provider_id'), 'ai_providers', ('organization_id', 'id')),
        ),
    ),
    'ai_providers': Table(
        'ai_providers',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('name', 'TEXT', False, False),
            Column('slug', 'public.slug', False, False),
            Column('description', 'TEXT', True, False),
            Column('icon', 'TEXT', True, False),
            Column('driver', 'TEXT', False, False),
            Column('base_url', 'TEXT', True, False),
            Column('enabled', 'BOOLEAN', False, True),
            Column('credentials_encrypted', 'TEXT', True, False),
            Column('credential_hint', 'TEXT', True, False),
            Column('credential_updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('region', 'TEXT', True, False),
            Column('cloud_project_id', 'TEXT', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('driver_valid', "(driver = ANY (ARRAY['anthropic'::text, 'openai'::text, 'openai_compatible'::text, 'bedrock'::text, 'vertex'::text]))"),
            Check('compatible_has_url', "((driver <> 'openai_compatible'::text) OR (base_url IS NOT NULL))"),
        ),
        uniques=(
            Unique('ai_providers_pkey', ('id',), None, False),
            Unique('ai_providers_organization_id_id_key', ('organization_id', 'id'), None, False),
            Unique('ai_providers_organization_id_slug_key', ('organization_id', 'slug'), None, False),
        ),
        foreign_keys=(
            ForeignKey('ai_providers_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
        ),
    ),
    'analysis_reports': Table(
        'analysis_reports',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('project_id', 'TEXT', False, False),
            Column('overall_status', 'TEXT', False, False),
            Column('triggered_by', 'TEXT', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
        ),
        checks=(
            Check('overall_status_valid', "(overall_status = ANY (ARRAY['pass'::text, 'warn'::text, 'fail'::text]))"),
        ),
        uniques=(
            Unique('analysis_reports_pkey', ('id',), None, False),
            Unique('analysis_reports_organization_id_id_key', ('organization_id', 'id'), None, False),
            Unique('analysis_reports_project_id_key', ('project_id',), None, False),
        ),
        foreign_keys=(
            ForeignKey('analysis_reports_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('analysis_reports_project_id_fkey', ('organization_id', 'project_id'), 'projects', ('organization_id', 'id')),
            ForeignKey('analysis_reports_triggered_by_fkey', ('triggered_by',), 'users', ('id',)),
        ),
    ),
    'analysis_results': Table(
        'analysis_results',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('report_id', 'TEXT', False, False),
            Column('slug', 'TEXT', False, False),
            Column('title', 'TEXT', False, False),
            Column('description', 'TEXT', False, False),
            Column('result_status', 'TEXT', False, False),
            Column('plugin_slug', 'TEXT', False, False),
            Column('integration_id', 'TEXT', False, False),
            Column('remediation', 'public.jsonb_object', True, False),
        ),
        checks=(
            Check('result_status_valid', "(result_status = ANY (ARRAY['pass'::text, 'warn'::text, 'fail'::text]))"),
            Check('slug_not_empty', "(slug <> ''::text)"),
        ),
        uniques=(
            Unique('analysis_results_pkey', ('report_id', 'integration_id', 'slug'), None, False),
        ),
        foreign_keys=(
            ForeignKey('analysis_results_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('analysis_results_report_id_fkey', ('organization_id', 'report_id'), 'analysis_reports', ('organization_id', 'id')),
        ),
    ),
    'api_keys': Table(
        'api_keys',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('principal_id', 'TEXT', False, False),
            Column('key_id', 'TEXT', False, False),
            Column('key_hash', 'TEXT', False, False),
            Column('name', 'TEXT', False, False),
            Column('description', 'TEXT', True, False),
            Column('scopes', 'TEXT[]', False, True),
            Column('expires_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('last_used_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('last_rotated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('revoked_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        uniques=(
            Unique('api_keys_pkey', ('id',), None, False),
            Unique('api_keys_key_id_key', ('key_id',), None, False),
        ),
        foreign_keys=(
            ForeignKey('api_keys_principal_id_fkey', ('principal_id',), 'principals', ('id',)),
        ),
    ),
    'blockers': Table(
        'blockers',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('release_id', 'TEXT', False, False),
            Column('blocker_type', 'TEXT', False, True),
            Column('description', 'TEXT', False, False),
            Column('external_ref', 'TEXT', True, False),
            Column('blocker_status', 'TEXT', False, True),
            Column('scope', 'TEXT', False, True),
            Column('created_by', 'TEXT', False, False),
            Column('resolved_by', 'TEXT', True, False),
            Column('resolved_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('resolution_note', 'TEXT', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('blocker_type_valid', "(blocker_type = ANY (ARRAY['build-failure'::text, 'drift'::text, 'product-review'::text, 'qa'::text, 'deploy-order'::text, 'dependency'::text, 'manual'::text]))"),
            Check('blocker_status_valid', "(blocker_status = ANY (ARRAY['open'::text, 'resolved'::text]))"),
            Check('scope_valid', "(scope = ANY (ARRAY['commit'::text, 'tag'::text]))"),
            Check('description_length', '((char_length(description) >= 1) AND (char_length(description) <= 500))'),
            Check('external_ref_length', '(char_length(external_ref) <= 200)'),
            Check('resolution_note_length', '(char_length(resolution_note) <= 500)'),
        ),
        uniques=(
            Unique('blockers_pkey', ('id',), None, False),
            Unique('blockers_open_ref_idx', ('organization_id', 'release_id', 'external_ref'), "((blocker_status = 'open'::text) AND (external_ref IS NOT NULL))", False),
        ),
        foreign_keys=(
            ForeignKey('blockers_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('blockers_release_id_fkey', ('organization_id', 'release_id'), 'releases', ('organization_id', 'id')),
        ),
    ),
    'blueprints': Table(
        'blueprints',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('name', 'TEXT', False, False),
            Column('slug', 'public.slug', False, False),
            Column('description', 'TEXT', True, False),
            Column('icon', 'TEXT', True, False),
            Column('kind', 'TEXT', False, True),
            Column('entity_type', 'TEXT', True, False),
            Column('source_type', 'TEXT', True, False),
            Column('target_type', 'TEXT', True, False),
            Column('edge_type', 'TEXT', True, False),
            Column('enabled', 'BOOLEAN', False, True),
            Column('priority', 'INTEGER', False, True),
            Column('filter', 'public.jsonb_object', True, False),
            Column('json_schema', 'public.jsonb_object', False, False),
            Column('version', 'INTEGER', False, True),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('kind_valid', "(kind = ANY (ARRAY['node'::text, 'relationship'::text]))"),
            Check('entity_type_valid', "(entity_type = ANY (ARRAY['Team'::text, 'Environment'::text, 'ProjectType'::text, 'Project'::text, 'Organization'::text, 'Integration'::text]))"),
            Check('kind_fields', "(((kind = 'node'::text) AND (entity_type IS NOT NULL) AND (source_type IS NULL) AND (target_type IS NULL) AND (edge_type IS NULL)) OR ((kind = 'relationship'::text) AND (entity_type IS NULL) AND (source_type IS NOT NULL) AND (target_type IS NOT NULL) AND (edge_type IS NOT NULL)))"),
        ),
        uniques=(
            Unique('blueprints_pkey', ('id',), None, False),
            Unique('blueprints_organization_id_kind_entity_type_slug_key', ('organization_id', 'kind', 'entity_type', 'slug'), None, True),
        ),
        foreign_keys=(
            ForeignKey('blueprints_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
        ),
    ),
    'client_credentials': Table(
        'client_credentials',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('service_account_id', 'TEXT', False, False),
            Column('client_id', 'TEXT', False, False),
            Column('client_secret_hash', 'TEXT', False, False),
            Column('name', 'TEXT', False, False),
            Column('description', 'TEXT', True, False),
            Column('scopes', 'TEXT[]', False, True),
            Column('expires_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('last_used_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('last_rotated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('revoked_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        uniques=(
            Unique('client_credentials_pkey', ('id',), None, False),
            Unique('client_credentials_client_id_key', ('client_id',), None, False),
        ),
        foreign_keys=(
            ForeignKey('client_credentials_service_account_id_fkey', ('service_account_id',), 'service_accounts', ('id',)),
        ),
    ),
    'comment_threads': Table(
        'comment_threads',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('document_id', 'TEXT', False, False),
            Column('kind', 'TEXT', False, True),
            Column('anchor_quote', 'TEXT', False, True),
            Column('anchor_prefix', 'TEXT', False, True),
            Column('anchor_suffix', 'TEXT', False, True),
            Column('anchor_start', 'INTEGER', False, True),
            Column('resolved_by', 'TEXT', True, False),
            Column('resolved_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('created_by', 'TEXT', False, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('kind_valid', "(kind = ANY (ARRAY['page'::text, 'inline'::text]))"),
            Check('inline_has_quote', "((kind <> 'inline'::text) OR (anchor_quote <> ''::text))"),
        ),
        uniques=(
            Unique('comment_threads_pkey', ('id',), None, False),
            Unique('comment_threads_organization_id_id_key', ('organization_id', 'id'), None, False),
        ),
        foreign_keys=(
            ForeignKey('comment_threads_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('comment_threads_document_id_fkey', ('organization_id', 'document_id'), 'documents', ('organization_id', 'id')),
        ),
    ),
    'comments': Table(
        'comments',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('thread_id', 'TEXT', False, False),
            Column('author', 'TEXT', False, False),
            Column('body', 'TEXT', False, False),
            Column('mentions', 'TEXT[]', False, True),
            Column('acknowledged_by', 'TEXT[]', False, True),
            Column('edited', 'BOOLEAN', False, True),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('body_not_empty', "(body <> ''::text)"),
        ),
        uniques=(
            Unique('comments_pkey', ('id',), None, False),
        ),
        foreign_keys=(
            ForeignKey('comments_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('comments_thread_id_fkey', ('organization_id', 'thread_id'), 'comment_threads', ('organization_id', 'id')),
        ),
    ),
    'component_advisories': Table(
        'component_advisories',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('component_release_id', 'TEXT', False, False),
            Column('advisory_id', 'TEXT', False, False),
            Column('url', 'TEXT', False, False),
            Column('title', 'TEXT', True, False),
            Column('created_by', 'TEXT', False, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        uniques=(
            Unique('component_advisories_pkey', ('organization_id', 'component_release_id', 'advisory_id'), None, False),
        ),
        foreign_keys=(
            ForeignKey('component_advisories_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('component_advisories_component_release_id_fkey', ('component_release_id',), 'component_releases', ('id',)),
            ForeignKey('component_advisories_advisory_id_fkey', ('advisory_id',), 'advisories', ('id',)),
        ),
    ),
    'component_governance': Table(
        'component_governance',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('component_id', 'TEXT', False, False),
            Column('governance_status', 'TEXT', False, False),
            Column('status_by', 'TEXT', False, False),
            Column('status_at', 'TIMESTAMP WITH TIME ZONE', False, True),
        ),
        checks=(
            Check('governance_status_valid', "(governance_status = ANY (ARRAY['deprecated'::text, 'forbidden'::text]))"),
        ),
        uniques=(
            Unique('component_governance_pkey', ('organization_id', 'component_id'), None, False),
        ),
        foreign_keys=(
            ForeignKey('component_governance_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('component_governance_component_id_fkey', ('component_id',), 'components', ('id',)),
        ),
    ),
    'component_identifiers': Table(
        'component_identifiers',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('component_id', 'TEXT', False, False),
            Column('kind', 'TEXT', False, False),
            Column('value', 'TEXT', False, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('kind_valid', "(kind = ANY (ARRAY['purl'::text, 'cpe'::text, 'bom-ref'::text, 'swid'::text]))"),
        ),
        uniques=(
            Unique('component_identifiers_pkey', ('id',), None, False),
            Unique('component_identifiers_kind_value_key', ('kind', 'value'), None, False),
        ),
        foreign_keys=(
            ForeignKey('component_identifiers_component_id_fkey', ('component_id',), 'components', ('id',)),
        ),
    ),
    'component_notes': Table(
        'component_notes',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('component_release_id', 'TEXT', False, False),
            Column('author', 'TEXT', False, False),
            Column('body', 'TEXT', False, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
        ),
        checks=(
            Check('body_length', '((char_length(body) >= 1) AND (char_length(body) <= 2000))'),
        ),
        uniques=(
            Unique('component_notes_pkey', ('id',), None, False),
        ),
        foreign_keys=(
            ForeignKey('component_notes_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('component_notes_component_release_id_fkey', ('component_release_id',), 'component_releases', ('id',)),
        ),
    ),
    'component_overrides': Table(
        'component_overrides',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('component_id', 'TEXT', False, False),
            Column('name', 'TEXT', True, False),
            Column('description', 'TEXT', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('has_override', '(num_nonnulls(name, description) >= 1)'),
        ),
        uniques=(
            Unique('component_overrides_pkey', ('organization_id', 'component_id'), None, False),
        ),
        foreign_keys=(
            ForeignKey('component_overrides_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('component_overrides_component_id_fkey', ('component_id',), 'components', ('id',)),
        ),
    ),
    'component_release_governance': Table(
        'component_release_governance',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('component_release_id', 'TEXT', False, False),
            Column('governance_status', 'TEXT', False, False),
            Column('status_by', 'TEXT', False, False),
            Column('status_at', 'TIMESTAMP WITH TIME ZONE', False, True),
        ),
        checks=(
            Check('governance_status_valid', "(governance_status = ANY (ARRAY['deprecated'::text, 'forbidden'::text]))"),
        ),
        uniques=(
            Unique('component_release_governance_pkey', ('organization_id', 'component_release_id'), None, False),
        ),
        foreign_keys=(
            ForeignKey('component_release_governance_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('component_release_governance_component_release_id_fkey', ('component_release_id',), 'component_releases', ('id',)),
        ),
    ),
    'component_release_overrides': Table(
        'component_release_overrides',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('component_release_id', 'TEXT', False, False),
            Column('license', 'TEXT', True, False),
            Column('supplier', 'TEXT', True, False),
            Column('hashes', 'public.jsonb_object', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('has_override', '(num_nonnulls(license, supplier, hashes) >= 1)'),
        ),
        uniques=(
            Unique('component_release_overrides_pkey', ('organization_id', 'component_release_id'), None, False),
        ),
        foreign_keys=(
            ForeignKey('component_release_overrides_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('component_release_overrides_component_release_id_fkey', ('component_release_id',), 'component_releases', ('id',)),
        ),
    ),
    'component_releases': Table(
        'component_releases',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('component_id', 'TEXT', False, False),
            Column('version', 'TEXT', False, False),
            Column('license', 'TEXT', True, False),
            Column('supplier', 'TEXT', True, False),
            Column('hashes', 'public.jsonb_object', False, True),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        uniques=(
            Unique('component_releases_pkey', ('id',), None, False),
            Unique('component_releases_component_id_version_key', ('component_id', 'version'), None, False),
        ),
        foreign_keys=(
            ForeignKey('component_releases_component_id_fkey', ('component_id',), 'components', ('id',)),
        ),
    ),
    'components': Table(
        'components',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('purl_name', 'TEXT', False, False),
            Column('name', 'TEXT', False, False),
            Column('ecosystem', 'TEXT', False, False),
            Column('description', 'TEXT', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        uniques=(
            Unique('components_pkey', ('id',), None, False),
            Unique('components_purl_name_key', ('purl_name',), None, False),
        ),
    ),
    'conversations': Table(
        'conversations',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('user_id', 'TEXT', False, False),
            Column('title', 'TEXT', True, False),
            Column('model_name', 'TEXT', False, False),
            Column('archived_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', False, True),
        ),
        uniques=(
            Unique('conversations_pkey', ('id',), None, False),
            Unique('conversations_organization_id_id_key', ('organization_id', 'id'), None, False),
        ),
        foreign_keys=(
            ForeignKey('conversations_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('conversations_user_id_fkey', ('user_id',), 'users', ('id',)),
        ),
    ),
    'deployments': Table(
        'deployments',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('project_id', 'TEXT', False, False),
            Column('environment_id', 'TEXT', False, False),
            Column('release_id', 'TEXT', True, False),
            Column('origin', 'TEXT', False, True),
            Column('deployment_status', 'TEXT', False, False),
            Column('note', 'TEXT', True, False),
            Column('external_run_id', 'TEXT', True, False),
            Column('external_run_url', 'TEXT', True, False),
            Column('performed_by', 'TEXT', True, False),
            Column('credential', 'TEXT', True, False),
            Column('release_tag', 'TEXT', True, False),
            Column('release_committish', 'TEXT', True, False),
            Column('history', 'public.jsonb_array', False, True),
            Column('transitioned_at', 'TIMESTAMP WITH TIME ZONE', False, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('deployment_status_valid', "(deployment_status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'success'::text, 'failed'::text, 'rolled_back'::text]))"),
            Check('origin_valid', "(origin = ANY (ARRAY['api'::text, 'gateway'::text, 'promote'::text, 'promote-watcher'::text, 'sweeper'::text, 'migration'::text]))"),
        ),
        uniques=(
            Unique('deployments_pkey', ('id',), None, False),
            Unique('deployments_run_idx', ('organization_id', 'project_id', 'external_run_id'), '(external_run_id IS NOT NULL)', False),
        ),
        foreign_keys=(
            ForeignKey('deployments_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('deployments_project_id_fkey', ('organization_id', 'project_id'), 'projects', ('organization_id', 'id')),
            ForeignKey('deployments_environment_id_fkey', ('organization_id', 'environment_id'), 'environments', ('organization_id', 'id')),
            ForeignKey('deployments_release_id_fkey', ('organization_id', 'release_id'), 'releases', ('organization_id', 'id')),
        ),
    ),
    'document_likes': Table(
        'document_likes',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('document_id', 'TEXT', False, False),
            Column('user_id', 'TEXT', False, False),
            Column('liked_at', 'TIMESTAMP WITH TIME ZONE', False, True),
        ),
        uniques=(
            Unique('document_likes_pkey', ('document_id', 'user_id'), None, False),
        ),
        foreign_keys=(
            ForeignKey('document_likes_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('document_likes_document_id_fkey', ('organization_id', 'document_id'), 'documents', ('organization_id', 'id')),
            ForeignKey('document_likes_user_id_fkey', ('user_id',), 'users', ('id',)),
        ),
    ),
    'document_tags': Table(
        'document_tags',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('document_id', 'TEXT', False, False),
            Column('tag_id', 'TEXT', False, False),
        ),
        uniques=(
            Unique('document_tags_pkey', ('document_id', 'tag_id'), None, False),
        ),
        foreign_keys=(
            ForeignKey('document_tags_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('document_tags_document_id_fkey', ('organization_id', 'document_id'), 'documents', ('organization_id', 'id')),
            ForeignKey('document_tags_tag_id_fkey', ('organization_id', 'tag_id'), 'tags', ('organization_id', 'id')),
        ),
    ),
    'document_templates': Table(
        'document_templates',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('name', 'TEXT', False, False),
            Column('slug', 'public.slug', False, False),
            Column('description', 'TEXT', True, False),
            Column('icon', 'TEXT', True, False),
            Column('template_type', 'TEXT', False, True),
            Column('title', 'TEXT', True, False),
            Column('content', 'TEXT', False, True),
            Column('sort_order', 'INTEGER', False, True),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('template_type_valid', "(template_type = ANY (ARRAY['project'::text, 'global'::text, 'user'::text, 'project_type'::text]))"),
        ),
        uniques=(
            Unique('document_templates_pkey', ('id',), None, False),
            Unique('document_templates_organization_id_id_key', ('organization_id', 'id'), None, False),
            Unique('document_templates_organization_id_slug_key', ('organization_id', 'slug'), None, False),
        ),
        foreign_keys=(
            ForeignKey('document_templates_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
        ),
    ),
    'documents': Table(
        'documents',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('project_id', 'TEXT', True, False),
            Column('project_type_id', 'TEXT', True, False),
            Column('user_id', 'TEXT', True, False),
            Column('title', 'TEXT', False, False),
            Column('content', 'TEXT', False, False),
            Column('is_pinned', 'BOOLEAN', False, True),
            Column('version', 'INTEGER', False, True),
            Column('created_by', 'TEXT', False, False),
            Column('updated_by', 'TEXT', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('one_attachment', '(num_nonnulls(project_id, project_type_id, user_id) <= 1)'),
            Check('title_length', '(char_length(title) <= 200)'),
            Check('version_positive', '(version >= 1)'),
        ),
        uniques=(
            Unique('documents_pkey', ('id',), None, False),
            Unique('documents_organization_id_id_key', ('organization_id', 'id'), None, False),
        ),
        foreign_keys=(
            ForeignKey('documents_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('documents_project_id_fkey', ('organization_id', 'project_id'), 'projects', ('organization_id', 'id')),
            ForeignKey('documents_project_type_id_fkey', ('organization_id', 'project_type_id'), 'project_types', ('organization_id', 'id')),
            ForeignKey('documents_user_id_fkey', ('user_id',), 'users', ('id',)),
        ),
    ),
    'embeddings': Table(
        'embeddings',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('node_label', 'TEXT', False, False),
            Column('node_id', 'TEXT', False, False),
            Column('attribute', 'TEXT', False, False),
            Column('chunk_index', 'INTEGER', False, True),
            Column('model_name', 'TEXT', False, True),
            Column('chunk_text', 'TEXT', False, False),
            Column('embedding', 'public.vector', False, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
        ),
        uniques=(
            Unique('embeddings_pkey', ('node_label', 'node_id', 'attribute', 'chunk_index', 'model_name'), None, False),
        ),
        foreign_keys=(
            ForeignKey('embeddings_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
        ),
    ),
    'environments': Table(
        'environments',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('name', 'TEXT', False, False),
            Column('slug', 'public.slug', False, False),
            Column('description', 'TEXT', True, False),
            Column('icon', 'TEXT', True, False),
            Column('sort_order', 'INTEGER', False, True),
            Column('label_color', 'TEXT', True, False),
            Column('can_deploy', 'BOOLEAN', False, True),
            Column('can_promote', 'BOOLEAN', False, True),
            Column('terminal', 'BOOLEAN', False, True),
            Column('allow_autonomous', 'BOOLEAN', False, True),
            Column('attributes', 'public.jsonb_object', False, True),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('label_color_valid', "(label_color ~ '^#[0-9A-Fa-f]{6}$'::text)"),
        ),
        uniques=(
            Unique('environments_pkey', ('id',), None, False),
            Unique('environments_organization_id_id_key', ('organization_id', 'id'), None, False),
            Unique('environments_organization_id_slug_key', ('organization_id', 'slug'), None, False),
        ),
        foreign_keys=(
            ForeignKey('environments_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
        ),
    ),
    'identity_connections': Table(
        'identity_connections',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('integration_id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', True, False),
            Column('user_id', 'TEXT', False, False),
            Column('subject', 'TEXT', False, False),
            Column('access_token_encrypted', 'TEXT', True, False),
            Column('refresh_token_encrypted', 'TEXT', True, False),
            Column('id_token_claims_encrypted', 'TEXT', True, False),
            Column('scopes', 'TEXT[]', False, True),
            Column('connection_status', 'TEXT', False, True),
            Column('expires_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('last_used_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('metadata', 'public.jsonb_object', False, True),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('connection_status_valid', "(connection_status = ANY (ARRAY['active'::text, 'revoked'::text, 'expired'::text]))"),
        ),
        uniques=(
            Unique('identity_connections_pkey', ('id',), None, False),
            Unique('identity_connections_integration_id_user_id_key', ('integration_id', 'user_id'), None, False),
            Unique('identity_connections_integration_id_subject_key', ('integration_id', 'subject'), None, False),
        ),
        foreign_keys=(
            ForeignKey('identity_connections_integration_id_fkey', ('integration_id',), 'integrations', ('id',)),
            ForeignKey('identity_connections_user_id_fkey', ('user_id',), 'users', ('id',)),
        ),
    ),
    'integrations': Table(
        'integrations',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', True, False),
            Column('team_id', 'TEXT', True, False),
            Column('plugin_slug', 'TEXT', False, False),
            Column('name', 'TEXT', False, False),
            Column('slug', 'public.slug', False, False),
            Column('description', 'TEXT', True, False),
            Column('icon', 'TEXT', True, False),
            Column('options', 'public.jsonb_object', False, True),
            Column('credentials_encrypted', 'public.jsonb_object', False, True),
            Column('capabilities', 'public.jsonb_object', False, True),
            Column('used_as_login', 'BOOLEAN', False, True),
            Column('vendor', 'TEXT', True, False),
            Column('service_url', 'TEXT', True, False),
            Column('category', 'TEXT', True, False),
            Column('integration_status', 'TEXT', False, True),
            Column('links', 'public.jsonb_object', False, True),
            Column('identifiers', 'public.jsonb_object', False, True),
            Column('attributes', 'public.jsonb_object', False, True),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('integration_status_valid', "(integration_status = ANY (ARRAY['active'::text, 'deprecated'::text, 'evaluating'::text, 'inactive'::text]))"),
            Check('slug_valid', "((slug)::text ~ '^[a-z][a-z0-9-]{1,63}$'::text)"),
            Check('login_is_instance', '((NOT used_as_login) OR (organization_id IS NULL))'),
        ),
        uniques=(
            Unique('integrations_pkey', ('id',), None, False),
            Unique('integrations_organization_id_id_key', ('organization_id', 'id'), None, False),
            Unique('integrations_organization_id_slug_key', ('organization_id', 'slug'), None, True),
            Unique('integrations_one_login_idx', ('organization_id',), 'used_as_login', True),
        ),
        foreign_keys=(
            ForeignKey('integrations_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('integrations_team_id_fkey', ('organization_id', 'team_id'), 'teams', ('organization_id', 'id')),
            ForeignKey('integrations_plugin_slug_fkey', ('plugin_slug',), 'plugin_registrations', ('slug',)),
        ),
    ),
    'issued_tokens': Table(
        'issued_tokens',
        columns=(
            Column('principal_id', 'TEXT', False, False),
            Column('jti', 'TEXT', False, False),
            Column('token_type', 'TEXT', False, False),
            Column('family_id', 'TEXT', True, False),
            Column('issued_at', 'TIMESTAMP WITH TIME ZONE', False, False),
            Column('expires_at', 'TIMESTAMP WITH TIME ZONE', False, False),
            Column('revoked_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
        ),
        checks=(
            Check('token_type_valid', "(token_type = ANY (ARRAY['access'::text, 'refresh'::text]))"),
        ),
        uniques=(
            Unique('issued_tokens_pkey', ('jti',), None, False),
        ),
        foreign_keys=(
            ForeignKey('issued_tokens_principal_id_fkey', ('principal_id',), 'principals', ('id',)),
        ),
    ),
    'link_definitions': Table(
        'link_definitions',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('name', 'TEXT', False, False),
            Column('slug', 'public.slug', False, False),
            Column('description', 'TEXT', True, False),
            Column('icon', 'TEXT', True, False),
            Column('url_template', 'TEXT', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        uniques=(
            Unique('link_definitions_pkey', ('id',), None, False),
            Unique('link_definitions_organization_id_slug_key', ('organization_id', 'slug'), None, False),
        ),
        foreign_keys=(
            ForeignKey('link_definitions_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
        ),
    ),
    'local_auth_settings': Table(
        'local_auth_settings',
        columns=(
            Column('singleton', 'BOOLEAN', False, True),
            Column('enabled', 'BOOLEAN', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('one_row', 'singleton'),
        ),
        uniques=(
            Unique('local_auth_settings_pkey', ('singleton',), None, False),
        ),
    ),
    'mcp_servers': Table(
        'mcp_servers',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('name', 'TEXT', False, False),
            Column('slug', 'public.slug', False, False),
            Column('description', 'TEXT', True, False),
            Column('icon', 'TEXT', True, False),
            Column('url', 'TEXT', False, False),
            Column('enabled', 'BOOLEAN', False, True),
            Column('tool_prefix', 'TEXT', True, False),
            Column('timeout_seconds', 'INTEGER', False, True),
            Column('verify_ssl', 'BOOLEAN', False, True),
            Column('ignored_tools', 'TEXT[]', False, True),
            Column('auth_type', 'TEXT', False, True),
            Column('static_header', 'TEXT', True, False),
            Column('static_value_encrypted', 'TEXT', True, False),
            Column('oauth_token_url', 'TEXT', True, False),
            Column('oauth_client_id', 'TEXT', True, False),
            Column('oauth_client_secret_encrypted', 'TEXT', True, False),
            Column('oauth_scope', 'TEXT', True, False),
            Column('server_status', 'TEXT', False, True),
            Column('last_tested_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('last_tested_latency_ms', 'INTEGER', True, False),
            Column('tools_discovered_count', 'INTEGER', True, False),
            Column('last_error', 'TEXT', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('auth_type_valid', "(auth_type = ANY (ARRAY['none'::text, 'static'::text, 'oauth_client_credentials'::text]))"),
            Check('server_status_valid', "(server_status = ANY (ARRAY['unknown'::text, 'healthy'::text, 'degraded'::text, 'unreachable'::text]))"),
            Check('static_complete', "((auth_type <> 'static'::text) OR ((static_header IS NOT NULL) AND (static_value_encrypted IS NOT NULL)))"),
            Check('oauth_complete', "((auth_type <> 'oauth_client_credentials'::text) OR ((oauth_token_url IS NOT NULL) AND (oauth_client_id IS NOT NULL) AND (oauth_client_secret_encrypted IS NOT NULL)))"),
            Check('timeout_positive', '(timeout_seconds > 0)'),
            Check('latency_positive', '(last_tested_latency_ms >= 0)'),
            Check('tools_positive', '(tools_discovered_count >= 0)'),
        ),
        uniques=(
            Unique('mcp_servers_pkey', ('id',), None, False),
            Unique('mcp_servers_organization_id_slug_key', ('organization_id', 'slug'), None, False),
        ),
        foreign_keys=(
            ForeignKey('mcp_servers_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
        ),
    ),
    'memberships': Table(
        'memberships',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('principal_id', 'TEXT', False, False),
            Column('role_id', 'TEXT', False, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        uniques=(
            Unique('memberships_pkey', ('organization_id', 'principal_id'), None, False),
        ),
        foreign_keys=(
            ForeignKey('memberships_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('memberships_principal_id_fkey', ('principal_id',), 'principals', ('id',)),
            ForeignKey('memberships_role_id_fkey', ('organization_id', 'role_id'), 'roles', ('organization_id', 'id')),
        ),
    ),
    'messages': Table(
        'messages',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('conversation_id', 'TEXT', False, False),
            Column('message_seq', 'INTEGER', False, False),
            Column('author_role', 'TEXT', False, False),
            Column('content', 'TEXT', False, True),
            Column('tool_use', 'public.jsonb_array', True, False),
            Column('tool_results', 'public.jsonb_array', True, False),
            Column('token_usage', 'public.jsonb_object', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
        ),
        checks=(
            Check('author_role_valid', "(author_role = ANY (ARRAY['user'::text, 'assistant'::text]))"),
            Check('message_seq_range', '(message_seq >= 0)'),
            Check('content_length', "((author_role <> 'user'::text) OR (char_length(content) <= 32768))"),
        ),
        uniques=(
            Unique('messages_pkey', ('id',), None, False),
            Unique('messages_conversation_id_message_seq_key', ('conversation_id', 'message_seq'), None, False),
        ),
        foreign_keys=(
            ForeignKey('messages_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('messages_conversation_id_fkey', ('organization_id', 'conversation_id'), 'conversations', ('organization_id', 'id')),
        ),
    ),
    'oauth_clients': Table(
        'oauth_clients',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('client_id', 'TEXT', False, False),
            Column('client_name', 'TEXT', True, False),
            Column('redirect_uris', 'TEXT[]', False, False),
            Column('grant_types', 'TEXT[]', False, True),
            Column('response_types', 'TEXT[]', False, True),
            Column('token_endpoint_auth_method', 'TEXT', False, True),
            Column('scope', 'TEXT', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('redirect_uris_not_empty', '(cardinality(redirect_uris) > 0)'),
        ),
        uniques=(
            Unique('oauth_clients_pkey', ('id',), None, False),
            Unique('oauth_clients_client_id_key', ('client_id',), None, False),
        ),
    ),
    'organizations': Table(
        'organizations',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('tenant_id', 'TEXT', False, False),
            Column('name', 'TEXT', False, False),
            Column('slug', 'public.slug', False, False),
            Column('description', 'TEXT', True, False),
            Column('icon', 'TEXT', True, False),
            Column('previous_slugs', 'TEXT[]', False, True),
            Column('tag_formats', 'public.jsonb_array', False, True),
            Column('document_analytics_identities', 'TEXT', False, True),
            Column('attributes', 'public.jsonb_object', False, True),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('document_analytics_valid', "(document_analytics_identities = ANY (ARRAY['enabled'::text, 'authors_only'::text, 'disabled'::text]))"),
        ),
        uniques=(
            Unique('organizations_pkey', ('id',), None, False),
            Unique('organizations_slug_key', ('slug',), None, False),
        ),
        foreign_keys=(
            ForeignKey('organizations_tenant_id_fkey', ('tenant_id',), 'tenants', ('id',)),
        ),
    ),
    'password_reset_tokens': Table(
        'password_reset_tokens',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('user_id', 'TEXT', False, False),
            Column('token_hash', 'TEXT', False, False),
            Column('expires_at', 'TIMESTAMP WITH TIME ZONE', False, False),
            Column('used_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
        ),
        uniques=(
            Unique('password_reset_tokens_pkey', ('id',), None, False),
            Unique('password_reset_tokens_token_hash_key', ('token_hash',), None, False),
        ),
        foreign_keys=(
            ForeignKey('password_reset_tokens_user_id_fkey', ('user_id',), 'users', ('id',)),
        ),
    ),
    'permissions': Table(
        'permissions',
        columns=(
            Column('name', 'TEXT', False, False),
            Column('resource_type', 'TEXT', False, False),
            Column('action', 'TEXT', False, False),
            Column('description', 'TEXT', True, False),
        ),
        checks=(
            Check('name_valid', "(name = ((resource_type || ':'::text) || action))"),
        ),
        uniques=(
            Unique('permissions_pkey', ('name',), None, False),
        ),
    ),
    'plugin_edges': Table(
        'plugin_edges',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('plugin_slug', 'TEXT', False, False),
            Column('edge_type', 'TEXT', False, False),
            Column('source_label', 'TEXT', False, False),
            Column('source_id', 'TEXT', False, False),
            Column('target_label', 'TEXT', False, False),
            Column('target_id', 'TEXT', False, False),
            Column('properties', 'public.jsonb_object', False, True),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
        ),
        uniques=(
            Unique('plugin_edges_pkey', ('source_id', 'edge_type', 'target_id'), None, False),
        ),
        foreign_keys=(
            ForeignKey('plugin_edges_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('plugin_edges_plugin_slug_fkey', ('plugin_slug',), 'plugin_registrations', ('slug',)),
            ForeignKey('plugin_edges_target_id_fkey', ('organization_id', 'target_id'), 'plugin_entities', ('organization_id', 'id')),
        ),
    ),
    'plugin_entities': Table(
        'plugin_entities',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('plugin_slug', 'TEXT', False, False),
            Column('label', 'TEXT', False, False),
            Column('data', 'public.jsonb_object', False, True),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        uniques=(
            Unique('plugin_entities_pkey', ('id',), None, False),
            Unique('plugin_entities_organization_id_id_key', ('organization_id', 'id'), None, False),
        ),
        foreign_keys=(
            ForeignKey('plugin_entities_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('plugin_entities_plugin_slug_fkey', ('plugin_slug',), 'plugin_registrations', ('slug',)),
        ),
    ),
    'plugin_entity_keys': Table(
        'plugin_entity_keys',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('entity_id', 'TEXT', False, False),
            Column('plugin_slug', 'TEXT', False, False),
            Column('label', 'TEXT', False, False),
            Column('index_name', 'TEXT', False, False),
            Column('key_value', 'public.jsonb_array', False, False),
        ),
        uniques=(
            Unique('plugin_entity_keys_pkey', ('entity_id', 'index_name'), None, False),
            Unique('plugin_entity_keys_organization_id_plugin_slug_label_index_name_key_value_key', ('organization_id', 'plugin_slug', 'label', 'index_name', 'key_value'), None, False),
        ),
        foreign_keys=(
            ForeignKey('plugin_entity_keys_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('plugin_entity_keys_entity_id_fkey', ('organization_id', 'entity_id'), 'plugin_entities', ('organization_id', 'id')),
        ),
    ),
    'plugin_registrations': Table(
        'plugin_registrations',
        columns=(
            Column('slug', 'public.slug', False, False),
            Column('enabled', 'BOOLEAN', False, True),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        uniques=(
            Unique('plugin_registrations_pkey', ('slug',), None, False),
        ),
    ),
    'principals': Table(
        'principals',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('principal_type', 'TEXT', False, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
        ),
        checks=(
            Check('principal_type_valid', "(principal_type = ANY (ARRAY['user'::text, 'service_account'::text]))"),
        ),
        uniques=(
            Unique('principals_pkey', ('id',), None, False),
            Unique('principals_id_principal_type_key', ('id', 'principal_type'), None, False),
        ),
    ),
    'project_capabilities': Table(
        'project_capabilities',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('project_id', 'TEXT', False, False),
            Column('integration_id', 'TEXT', False, False),
            Column('capability', 'TEXT', False, False),
            Column('is_default', 'BOOLEAN', False, True),
            Column('options', 'public.jsonb_object', False, True),
            Column('environment_payloads', 'public.jsonb_object', True, False),
            Column('identity_integration_id', 'TEXT', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        uniques=(
            Unique('project_capabilities_pkey', ('project_id', 'integration_id', 'capability'), None, False),
        ),
        foreign_keys=(
            ForeignKey('project_capabilities_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('project_capabilities_project_id_fkey', ('organization_id', 'project_id'), 'projects', ('organization_id', 'id')),
            ForeignKey('project_capabilities_integration_id_fkey', ('organization_id', 'integration_id'), 'integrations', ('organization_id', 'id')),
            ForeignKey('project_capabilities_identity_integration_id_fkey', ('organization_id', 'identity_integration_id'), 'integrations', ('organization_id', 'id')),
        ),
    ),
    'project_dependencies': Table(
        'project_dependencies',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('project_id', 'TEXT', False, False),
            Column('dependency_id', 'TEXT', False, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
        ),
        checks=(
            Check('not_self', '(project_id <> dependency_id)'),
        ),
        uniques=(
            Unique('project_dependencies_pkey', ('project_id', 'dependency_id'), None, False),
        ),
        foreign_keys=(
            ForeignKey('project_dependencies_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('project_dependencies_project_id_fkey', ('organization_id', 'project_id'), 'projects', ('organization_id', 'id')),
            ForeignKey('project_dependencies_dependency_id_fkey', ('organization_id', 'dependency_id'), 'projects', ('organization_id', 'id')),
        ),
    ),
    'project_environments': Table(
        'project_environments',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('project_id', 'TEXT', False, False),
            Column('environment_id', 'TEXT', False, False),
            Column('attributes', 'public.jsonb_object', False, True),
            Column('current_release_id', 'TEXT', True, False),
            Column('current_release_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('current_deployment_external_id', 'TEXT', True, False),
            Column('current_state_source', 'TEXT', True, False),
            Column('current_state_observed_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('current_state_source_valid', "(current_state_source = ANY (ARRAY['reconcile'::text]))"),
        ),
        uniques=(
            Unique('project_environments_pkey', ('project_id', 'environment_id'), None, False),
        ),
        foreign_keys=(
            ForeignKey('project_environments_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('project_environments_project_id_fkey', ('organization_id', 'project_id'), 'projects', ('organization_id', 'id')),
            ForeignKey('project_environments_environment_id_fkey', ('organization_id', 'environment_id'), 'environments', ('organization_id', 'id')),
            ForeignKey('project_environments_current_release_id_fkey', ('organization_id', 'current_release_id'), 'releases', ('organization_id', 'id')),
        ),
    ),
    'project_integrations': Table(
        'project_integrations',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('project_id', 'TEXT', False, False),
            Column('integration_id', 'TEXT', False, False),
            Column('identifier', 'TEXT', False, False),
            Column('canonical_url', 'TEXT', True, False),
            Column('webhook_secret_encrypted', 'TEXT', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('identifier_not_empty', "(identifier <> ''::text)"),
        ),
        uniques=(
            Unique('project_integrations_pkey', ('project_id', 'integration_id'), None, False),
        ),
        foreign_keys=(
            ForeignKey('project_integrations_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('project_integrations_project_id_fkey', ('organization_id', 'project_id'), 'projects', ('organization_id', 'id')),
            ForeignKey('project_integrations_integration_id_fkey', ('organization_id', 'integration_id'), 'integrations', ('organization_id', 'id')),
        ),
    ),
    'project_promotions': Table(
        'project_promotions',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('project_id', 'TEXT', False, False),
            Column('promotion_status', 'TEXT', False, True),
            Column('status_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('status_by', 'TEXT', True, False),
            Column('tag', 'TEXT', True, False),
            Column('committish', 'TEXT', True, False),
            Column('environment_id', 'TEXT', True, False),
            Column('from_environment_id', 'TEXT', True, False),
            Column('run_id', 'TEXT', True, False),
            Column('run_url', 'TEXT', True, False),
            Column('error', 'TEXT', True, False),
        ),
        checks=(
            Check('promotion_status_valid', "(promotion_status = ANY (ARRAY['idle'::text, 'building'::text, 'deploying'::text, 'success'::text, 'build_failed'::text, 'deploy_failed'::text, 'failed'::text]))"),
        ),
        uniques=(
            Unique('project_promotions_pkey', ('project_id',), None, False),
        ),
        foreign_keys=(
            ForeignKey('project_promotions_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('project_promotions_project_id_fkey', ('organization_id', 'project_id'), 'projects', ('organization_id', 'id')),
            ForeignKey('project_promotions_environment_id_fkey', ('organization_id', 'environment_id'), 'environments', ('organization_id', 'id')),
            ForeignKey('project_promotions_from_environment_id_fkey', ('organization_id', 'from_environment_id'), 'environments', ('organization_id', 'id')),
        ),
    ),
    'project_syncs': Table(
        'project_syncs',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('project_id', 'TEXT', False, False),
            Column('sync_type', 'TEXT', False, False),
            Column('sync_status', 'TEXT', False, True),
            Column('status_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('status_by', 'TEXT', True, False),
            Column('result', 'public.jsonb_object', False, True),
            Column('error', 'TEXT', True, False),
        ),
        checks=(
            Check('sync_type_valid', "(sync_type = ANY (ARRAY['commit'::text, 'deployment'::text, 'pull_request'::text]))"),
            Check('sync_status_valid', "(sync_status = ANY (ARRAY['idle'::text, 'queued'::text, 'running'::text, 'success'::text, 'failed'::text]))"),
        ),
        uniques=(
            Unique('project_syncs_pkey', ('project_id', 'sync_type'), None, False),
        ),
        foreign_keys=(
            ForeignKey('project_syncs_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('project_syncs_project_id_fkey', ('organization_id', 'project_id'), 'projects', ('organization_id', 'id')),
        ),
    ),
    'project_type_assignments': Table(
        'project_type_assignments',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('project_id', 'TEXT', False, False),
            Column('project_type_id', 'TEXT', False, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
        ),
        uniques=(
            Unique('project_type_assignments_pkey', ('project_id', 'project_type_id'), None, False),
        ),
        foreign_keys=(
            ForeignKey('project_type_assignments_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('project_type_assignments_project_id_fkey', ('organization_id', 'project_id'), 'projects', ('organization_id', 'id')),
            ForeignKey('project_type_assignments_project_type_id_fkey', ('organization_id', 'project_type_id'), 'project_types', ('organization_id', 'id')),
        ),
    ),
    'project_type_capabilities': Table(
        'project_type_capabilities',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('project_type_id', 'TEXT', False, False),
            Column('integration_id', 'TEXT', False, False),
            Column('capability', 'TEXT', False, False),
            Column('is_default', 'BOOLEAN', False, True),
            Column('options', 'public.jsonb_object', False, True),
            Column('environment_payloads', 'public.jsonb_object', True, False),
            Column('identity_integration_id', 'TEXT', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        uniques=(
            Unique('project_type_capabilities_pkey', ('project_type_id', 'integration_id', 'capability'), None, False),
        ),
        foreign_keys=(
            ForeignKey('project_type_capabilities_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('project_type_capabilities_project_type_id_fkey', ('organization_id', 'project_type_id'), 'project_types', ('organization_id', 'id')),
            ForeignKey('project_type_capabilities_integration_id_fkey', ('organization_id', 'integration_id'), 'integrations', ('organization_id', 'id')),
            ForeignKey('project_type_capabilities_identity_integration_id_fkey', ('organization_id', 'identity_integration_id'), 'integrations', ('organization_id', 'id')),
        ),
    ),
    'project_types': Table(
        'project_types',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('name', 'TEXT', False, False),
            Column('slug', 'public.slug', False, False),
            Column('description', 'TEXT', True, False),
            Column('icon', 'TEXT', True, False),
            Column('deployable', 'BOOLEAN', False, True),
            Column('releasable', 'BOOLEAN', False, True),
            Column('tag_formats', 'public.jsonb_array', False, True),
            Column('attributes', 'public.jsonb_object', False, True),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('deployable_or_releasable', '(NOT (deployable AND releasable))'),
        ),
        uniques=(
            Unique('project_types_pkey', ('id',), None, False),
            Unique('project_types_organization_id_id_key', ('organization_id', 'id'), None, False),
            Unique('project_types_organization_id_slug_key', ('organization_id', 'slug'), None, False),
        ),
        foreign_keys=(
            ForeignKey('project_types_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
        ),
    ),
    'projects': Table(
        'projects',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('team_id', 'TEXT', False, False),
            Column('name', 'TEXT', False, False),
            Column('slug', 'public.slug', False, False),
            Column('description', 'TEXT', True, False),
            Column('icon', 'TEXT', True, False),
            Column('links', 'public.jsonb_object', False, True),
            Column('identifiers', 'public.jsonb_object', False, True),
            Column('attributes', 'public.jsonb_object', False, True),
            Column('score', 'NUMERIC', True, False),
            Column('previous_score', 'NUMERIC', True, False),
            Column('archived_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('drift_verdicts_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        uniques=(
            Unique('projects_pkey', ('id',), None, False),
            Unique('projects_organization_id_id_key', ('organization_id', 'id'), None, False),
        ),
        foreign_keys=(
            ForeignKey('projects_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('projects_team_id_fkey', ('organization_id', 'team_id'), 'teams', ('organization_id', 'id')),
        ),
    ),
    'releases': Table(
        'releases',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('project_id', 'TEXT', False, False),
            Column('tag', 'TEXT', True, False),
            Column('committish', 'TEXT', False, False),
            Column('promoted_committish', 'TEXT', True, False),
            Column('title', 'TEXT', False, False),
            Column('description', 'TEXT', True, False),
            Column('links', 'public.jsonb_array', False, True),
            Column('created_by', 'TEXT', False, False),
            Column('workflow_run_id', 'TEXT', True, False),
            Column('workflow_run_url', 'TEXT', True, False),
            Column('promote_ci_status', 'TEXT', True, False),
            Column('ci_override_by', 'TEXT', True, False),
            Column('ci_override_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('drift_detected', 'BOOLEAN', True, False),
            Column('drift_checked_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('tag_not_empty', "(tag <> ''::text)"),
            Check('promote_ci_status_valid', "(promote_ci_status = ANY (ARRAY['pass'::text, 'fail'::text, 'warn'::text, 'unknown'::text]))"),
        ),
        uniques=(
            Unique('releases_pkey', ('id',), None, False),
            Unique('releases_organization_id_id_key', ('organization_id', 'id'), None, False),
            Unique('releases_project_tag_idx', ('organization_id', 'project_id', 'tag'), '(tag IS NOT NULL)', False),
            Unique('releases_project_commit_idx', ('organization_id', 'project_id', 'committish'), '(tag IS NULL)', False),
        ),
        foreign_keys=(
            ForeignKey('releases_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('releases_project_id_fkey', ('organization_id', 'project_id'), 'projects', ('organization_id', 'id')),
        ),
    ),
    'resource_acls': Table(
        'resource_acls',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('principal_id', 'TEXT', False, False),
            Column('resource_type', 'TEXT', False, False),
            Column('resource_slug', 'TEXT', False, False),
            Column('actions', 'TEXT[]', False, True),
            Column('granted_by', 'TEXT', True, False),
            Column('granted_at', 'TIMESTAMP WITH TIME ZONE', False, True),
        ),
        checks=(
            Check('resource_type_valid', "(resource_type = ANY (ARRAY['blueprint'::text, 'document'::text, 'document_template'::text, 'environment'::text, 'identity_connection'::text, 'integration'::text, 'link_definition'::text, 'organization'::text, 'project'::text, 'project_type'::text, 'release'::text, 'role'::text, 'tag'::text, 'team'::text]))"),
        ),
        uniques=(
            Unique('resource_acls_pkey', ('organization_id', 'principal_id', 'resource_type', 'resource_slug'), None, False),
        ),
        foreign_keys=(
            ForeignKey('resource_acls_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('resource_acls_principal_id_fkey', ('principal_id',), 'principals', ('id',)),
        ),
    ),
    'role_grants': Table(
        'role_grants',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('role_id', 'TEXT', False, False),
            Column('permission_name', 'TEXT', False, False),
        ),
        uniques=(
            Unique('role_grants_pkey', ('role_id', 'permission_name'), None, False),
        ),
        foreign_keys=(
            ForeignKey('role_grants_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('role_grants_role_id_fkey', ('organization_id', 'role_id'), 'roles', ('organization_id', 'id')),
            ForeignKey('role_grants_permission_name_fkey', ('permission_name',), 'permissions', ('name',)),
        ),
    ),
    'roles': Table(
        'roles',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('name', 'TEXT', False, False),
            Column('slug', 'public.slug', False, False),
            Column('description', 'TEXT', True, False),
            Column('icon', 'TEXT', True, False),
            Column('parent_role_id', 'TEXT', True, False),
            Column('priority', 'INTEGER', False, True),
            Column('is_system', 'BOOLEAN', False, True),
            Column('is_default', 'BOOLEAN', False, True),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('not_own_parent', '(parent_role_id <> id)'),
        ),
        uniques=(
            Unique('roles_pkey', ('id',), None, False),
            Unique('roles_organization_id_id_key', ('organization_id', 'id'), None, False),
            Unique('roles_organization_id_slug_key', ('organization_id', 'slug'), None, False),
            Unique('roles_one_default_idx', ('organization_id',), 'is_default', False),
        ),
        foreign_keys=(
            ForeignKey('roles_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('roles_parent_role_id_fkey', ('organization_id', 'parent_role_id'), 'roles', ('organization_id', 'id')),
        ),
    ),
    'scoring_policies': Table(
        'scoring_policies',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('name', 'TEXT', False, False),
            Column('slug', 'public.slug', False, False),
            Column('description', 'TEXT', True, False),
            Column('category', 'TEXT', False, True),
            Column('weight', 'SMALLINT', False, False),
            Column('enabled', 'BOOLEAN', False, True),
            Column('priority', 'INTEGER', False, True),
            Column('parameters', 'public.jsonb_object', False, True),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('category_valid', "(category = ANY (ARRAY['attribute'::text, 'presence'::text, 'link_presence'::text, 'analysis_result'::text, 'deployment_status'::text, 'age'::text, 'condition'::text]))"),
            Check('weight_range', '((weight >= 0) AND (weight <= 100))'),
            Check('parameters_match_category', "CASE category\n    WHEN 'attribute'::text THEN ((((parameters)::jsonb ->> 'attribute_name'::text) IS NOT NULL) AND (COALESCE((jsonb_typeof(((parameters)::jsonb -> 'value_score_map'::text)) = 'object'::text), false) <> COALESCE((jsonb_typeof(((parameters)::jsonb -> 'range_score_map'::text)) = 'object'::text), false)))\n    WHEN 'presence'::text THEN (((parameters)::jsonb ->> 'attribute_name'::text) IS NOT NULL)\n    WHEN 'link_presence'::text THEN (((parameters)::jsonb ->> 'link_slug'::text) IS NOT NULL)\n    WHEN 'analysis_result'::text THEN (((parameters)::jsonb ->> 'result_slug'::text) IS NOT NULL)\n    WHEN 'deployment_status'::text THEN (((parameters)::jsonb ->> 'environment_slug'::text) IS NOT NULL)\n    WHEN 'age'::text THEN ((((parameters)::jsonb ->> 'attribute_name'::text) IS NOT NULL) AND COALESCE((jsonb_typeof(((parameters)::jsonb -> 'age_score_map'::text)) = 'object'::text), false))\n    WHEN 'condition'::text THEN COALESCE((jsonb_typeof(((parameters)::jsonb -> 'condition'::text)) = 'object'::text), false)\n    ELSE false\nEND"),
        ),
        uniques=(
            Unique('scoring_policies_pkey', ('id',), None, False),
            Unique('scoring_policies_organization_id_id_key', ('organization_id', 'id'), None, False),
            Unique('scoring_policies_organization_id_slug_key', ('organization_id', 'slug'), None, False),
        ),
        foreign_keys=(
            ForeignKey('scoring_policies_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
        ),
    ),
    'scoring_policy_targets': Table(
        'scoring_policy_targets',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('scoring_policy_id', 'TEXT', False, False),
            Column('project_type_id', 'TEXT', False, False),
        ),
        uniques=(
            Unique('scoring_policy_targets_pkey', ('scoring_policy_id', 'project_type_id'), None, False),
        ),
        foreign_keys=(
            ForeignKey('scoring_policy_targets_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('scoring_policy_targets_scoring_policy_id_fkey', ('organization_id', 'scoring_policy_id'), 'scoring_policies', ('organization_id', 'id')),
            ForeignKey('scoring_policy_targets_project_type_id_fkey', ('organization_id', 'project_type_id'), 'project_types', ('organization_id', 'id')),
        ),
    ),
    'service_accounts': Table(
        'service_accounts',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('principal_type', 'TEXT', False, True),
            Column('slug', 'public.slug', False, False),
            Column('display_name', 'TEXT', False, False),
            Column('description', 'TEXT', True, False),
            Column('is_active', 'BOOLEAN', False, True),
            Column('avatar_url', 'TEXT', True, False),
            Column('last_authenticated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('principal_type_valid', "(principal_type = 'service_account'::text)"),
            Check('slug_valid', "((slug)::text ~ '^[a-z][a-z0-9-]{1,63}$'::text)"),
        ),
        uniques=(
            Unique('service_accounts_pkey', ('id',), None, False),
            Unique('service_accounts_slug_key', ('slug',), None, False),
        ),
        foreign_keys=(
            ForeignKey('service_accounts_id_principal_type_fkey', ('id', 'principal_type'), 'principals', ('id', 'principal_type')),
        ),
    ),
    'tags': Table(
        'tags',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('name', 'TEXT', False, False),
            Column('slug', 'public.slug', False, False),
            Column('description', 'TEXT', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('name_not_empty', "(name <> ''::text)"),
        ),
        uniques=(
            Unique('tags_pkey', ('id',), None, False),
            Unique('tags_organization_id_id_key', ('organization_id', 'id'), None, False),
            Unique('tags_organization_id_slug_key', ('organization_id', 'slug'), None, False),
        ),
        foreign_keys=(
            ForeignKey('tags_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
        ),
    ),
    'team_members': Table(
        'team_members',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('team_id', 'TEXT', False, False),
            Column('user_id', 'TEXT', False, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
        ),
        uniques=(
            Unique('team_members_pkey', ('team_id', 'user_id'), None, False),
        ),
        foreign_keys=(
            ForeignKey('team_members_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('team_members_team_id_fkey', ('organization_id', 'team_id'), 'teams', ('organization_id', 'id')),
            ForeignKey('team_members_user_id_fkey', ('user_id',), 'users', ('id',)),
        ),
    ),
    'teams': Table(
        'teams',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('name', 'TEXT', False, False),
            Column('slug', 'public.slug', False, False),
            Column('description', 'TEXT', True, False),
            Column('icon', 'TEXT', True, False),
            Column('attributes', 'public.jsonb_object', False, True),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        uniques=(
            Unique('teams_pkey', ('id',), None, False),
            Unique('teams_organization_id_id_key', ('organization_id', 'id'), None, False),
            Unique('teams_organization_id_slug_key', ('organization_id', 'slug'), None, False),
        ),
        foreign_keys=(
            ForeignKey('teams_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
        ),
    ),
    'template_project_types': Table(
        'template_project_types',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('document_template_id', 'TEXT', False, False),
            Column('project_type_id', 'TEXT', False, False),
        ),
        uniques=(
            Unique('template_project_types_pkey', ('document_template_id', 'project_type_id'), None, False),
        ),
        foreign_keys=(
            ForeignKey('template_project_types_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('template_project_types_document_template_id_fkey', ('organization_id', 'document_template_id'), 'document_templates', ('organization_id', 'id')),
            ForeignKey('template_project_types_project_type_id_fkey', ('organization_id', 'project_type_id'), 'project_types', ('organization_id', 'id')),
        ),
    ),
    'template_tags': Table(
        'template_tags',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('document_template_id', 'TEXT', False, False),
            Column('tag_id', 'TEXT', False, False),
        ),
        uniques=(
            Unique('template_tags_pkey', ('document_template_id', 'tag_id'), None, False),
        ),
        foreign_keys=(
            ForeignKey('template_tags_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('template_tags_document_template_id_fkey', ('organization_id', 'document_template_id'), 'document_templates', ('organization_id', 'id')),
            ForeignKey('template_tags_tag_id_fkey', ('organization_id', 'tag_id'), 'tags', ('organization_id', 'id')),
        ),
    ),
    'tenants': Table(
        'tenants',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('name', 'TEXT', False, False),
            Column('slug', 'public.slug', False, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        uniques=(
            Unique('tenants_pkey', ('id',), None, False),
            Unique('tenants_slug_key', ('slug',), None, False),
        ),
    ),
    'totp_secrets': Table(
        'totp_secrets',
        columns=(
            Column('user_id', 'TEXT', False, False),
            Column('secret_encrypted', 'TEXT', False, False),
            Column('enabled', 'BOOLEAN', False, True),
            Column('backup_code_hashes', 'TEXT[]', False, True),
            Column('last_used_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        uniques=(
            Unique('totp_secrets_pkey', ('user_id',), None, False),
        ),
        foreign_keys=(
            ForeignKey('totp_secrets_user_id_fkey', ('user_id',), 'users', ('id',)),
        ),
    ),
    'uploads': Table(
        'uploads',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('filename', 'TEXT', False, False),
            Column('content_type', 'TEXT', False, False),
            Column('file_size', 'BIGINT', False, False),
            Column('storage_key', 'TEXT', False, False),
            Column('thumbnail_storage_key', 'TEXT', True, False),
            Column('uploaded_by', 'TEXT', False, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
        ),
        checks=(
            Check('file_size_range', '(file_size >= 0)'),
        ),
        uniques=(
            Unique('uploads_pkey', ('id',), None, False),
            Unique('uploads_storage_key_key', ('storage_key',), None, False),
        ),
        foreign_keys=(
            ForeignKey('uploads_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
        ),
    ),
    'users': Table(
        'users',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('principal_type', 'TEXT', False, True),
            Column('email', 'TEXT', False, False),
            Column('display_name', 'TEXT', False, False),
            Column('password_hash', 'TEXT', True, False),
            Column('is_active', 'BOOLEAN', False, True),
            Column('is_admin', 'BOOLEAN', False, True),
            Column('email_notifications', 'BOOLEAN', False, True),
            Column('avatar_url', 'TEXT', True, False),
            Column('last_login_at', 'TIMESTAMP WITH TIME ZONE', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('principal_type_valid', "(principal_type = 'user'::text)"),
        ),
        uniques=(
            Unique('users_pkey', ('id',), None, False),
            Unique('users_email_idx', ('lower(email)',), None, False),
        ),
        foreign_keys=(
            ForeignKey('users_id_principal_type_fkey', ('id', 'principal_type'), 'principals', ('id', 'principal_type')),
        ),
    ),
    'webhook_rules': Table(
        'webhook_rules',
        columns=(
            Column('organization_id', 'TEXT', False, False),
            Column('webhook_id', 'TEXT', False, False),
            Column('ordinal', 'SMALLINT', False, False),
            Column('filter_expression', 'TEXT', False, False),
            Column('handler', 'TEXT', False, False),
            Column('handler_config', 'JSONB', False, True),
        ),
        checks=(
            Check('ordinal_range', '(ordinal >= 0)'),
            Check('handler_valid', "(handler ~ '^[a-z][a-z0-9-]*#[a-z][a-z0-9_]*$'::text)"),
            Check('filter_not_empty', "(filter_expression <> ''::text)"),
        ),
        uniques=(
            Unique('webhook_rules_pkey', ('webhook_id', 'ordinal'), None, False),
        ),
        foreign_keys=(
            ForeignKey('webhook_rules_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('webhook_rules_webhook_id_fkey', ('organization_id', 'webhook_id'), 'webhooks', ('organization_id', 'id')),
        ),
    ),
    'webhooks': Table(
        'webhooks',
        columns=(
            Column('id', 'TEXT', False, False),
            Column('organization_id', 'TEXT', False, False),
            Column('name', 'TEXT', False, False),
            Column('slug', 'public.slug', False, False),
            Column('description', 'TEXT', True, False),
            Column('icon', 'TEXT', True, False),
            Column('integration_id', 'TEXT', True, False),
            Column('secret_encrypted', 'TEXT', True, False),
            Column('identifier_selector', 'TEXT', True, False),
            Column('user_subject_selector', 'TEXT', True, False),
            Column('user_type_selector', 'TEXT', True, False),
            Column('identity_integration_id', 'TEXT', True, False),
            Column('event_type_selector', 'TEXT', True, False),
            Column('created_at', 'TIMESTAMP WITH TIME ZONE', False, True),
            Column('updated_at', 'TIMESTAMP WITH TIME ZONE', True, False),
        ),
        checks=(
            Check('slug_valid', "((slug)::text ~ '^[a-z][a-z0-9-]{1,63}$'::text)"),
            Check('selectors_need_integration', '((integration_id IS NOT NULL) OR ((identifier_selector IS NULL) AND (user_subject_selector IS NULL) AND (user_type_selector IS NULL) AND (identity_integration_id IS NULL) AND (event_type_selector IS NULL)))'),
        ),
        uniques=(
            Unique('webhooks_pkey', ('id',), None, False),
            Unique('webhooks_organization_id_id_key', ('organization_id', 'id'), None, False),
            Unique('webhooks_organization_id_slug_key', ('organization_id', 'slug'), None, False),
        ),
        foreign_keys=(
            ForeignKey('webhooks_organization_id_fkey', ('organization_id',), 'organizations', ('id',)),
            ForeignKey('webhooks_integration_id_fkey', ('organization_id', 'integration_id'), 'integrations', ('organization_id', 'id')),
            ForeignKey('webhooks_identity_integration_id_fkey', ('identity_integration_id',), 'integrations', ('id',)),
        ),
    ),
}
# fmt: on
