"""
Application Views

"""
from tornado import web

from . import (
    configuration_systems,
    cookie_cutters,
    data_centers,
    deployment_types,
    environments,
    groups,
    namespaces,
    openapi,
    operations,
    orchestration_systems,
    project,
    project_fact_type_options,
    project_fact_types,
    project_link_types,
    project_types,
    settings,
    status,
    ui
)

URLS = [
           web.url(r'^/$', ui.IndexRequestHandler),
           web.url(r'^/api-docs/$', openapi.RequestHandler),
           web.url(r'^/api-docs/(openapi.yaml)$', openapi.RequestHandler),
           web.url(r'/configuration_systems',
                   configuration_systems.AdminCRUDRequestHandler),
           web.url(r'/configuration_systems/(?P<name>[\w_\-%\+]+)',
                   configuration_systems.AdminCRUDRequestHandler,
                   name='admin-configuration-systems'),
           web.url(r'/cookie_cutters', cookie_cutters.AdminCRUDRequestHandler),
           web.url(r'/cookie_cutters/(?P<name>[\w_\-%\+]+)',
                   cookie_cutters.AdminCRUDRequestHandler,
                   name='admin-cookie-cutters'),
           web.url(r'/deployment_types',
                   deployment_types.AdminCRUDRequestHandler),
           web.url(r'/deployment_types/(?P<name>[\w_\-%\+]+)',
                   deployment_types.AdminCRUDRequestHandler,
                   name='admin-deployment-types'),
           web.url(r'/data_centers', data_centers.AdminCRUDRequestHandler),
           web.url(r'/data_centers/(?P<name>[\w_\-%\+]+)',
                   data_centers.AdminCRUDRequestHandler,
                   name='admin-data-centers'),
           web.url(r'/environments', environments.AdminCRUDRequestHandler),
           web.url(r'/environments/(?P<name>[\w_\-%\+]+)',
                   environments.AdminCRUDRequestHandler,
                   name='admin-environments'),
           web.url(r'/groups', groups.AdminCRUDRequestHandler),
           web.url(r'/groups/(?P<name>[\w_\-%\+]+)',
                   groups.AdminCRUDRequestHandler,
                   name='admin-groups'),
           web.url(r'/namespaces', namespaces.AdminCRUDRequestHandler),
           web.url(r'/namespaces/(?P<id>\d+)',
                   namespaces.AdminCRUDRequestHandler,
                   name='admin-namespaces'),
           web.url(r'/orchestration_systems',
                   orchestration_systems.AdminCRUDRequestHandler),
           web.url(r'/orchestration_systems/(?P<name>[\w_\-%\+]+)',
                   orchestration_systems.AdminCRUDRequestHandler,
                   name='admin-orchestration-systems'),
           web.url(r'/project_fact_types',
                   project_fact_types.AdminCRUDRequestHandler),
           web.url(r'/project_fact_types/(?P<id>\d+)',
                   project_fact_types.AdminCRUDRequestHandler,
                   name='admin-project-fact-types'),
           web.url(r'/project_fact_type_options',
                   project_fact_type_options.AdminCRUDRequestHandler),
           web.url(r'/project_fact_type_options/(?P<id>\d+)',
                   project_fact_type_options.AdminCRUDRequestHandler,
                   name='admin-project-fact-type-options'),
           web.url(r'/project_link_types',
                   project_link_types.AdminCRUDRequestHandler),
           web.url(r'/project_link_types/(?P<id>\d+)',
                   project_link_types.AdminCRUDRequestHandler,
                   name='admin-project-link-types'),
           web.url(r'/project_types', project_types.AdminCRUDRequestHandler),
           web.url(r'/project_types/(?P<id>\d+)',
                   project_types.AdminCRUDRequestHandler,
                   name='admin-project-types'),
           web.url(r'^/status$', status.RequestHandler),
           web.url(r'^/ui/groups$', ui.GroupsRequestHandler),
           web.url(r'^/ui/login$', ui.LoginRequestHandler),
           web.url(r'^/ui/logout$', ui.LogoutRequestHandler),
           web.url(r'^/ui/user$', ui.UserRequestHandler),
           web.url(r'^/ui/.*$', ui.IndexRequestHandler)
       ] + operations.URLS + project.URLS + settings.URLS
