from collections.abc import Callable
from typing import Any

from celpy import celtypes as celtypes

CELFunction = Callable[..., Any]

class CELEvalError(Exception): ...

class Runner:
    def evaluate(self, context: object) -> Any: ...

class Environment:
    def __init__(self) -> None: ...
    def compile(self, text: str) -> Any: ...
    def program(
        self, expr: Any, functions: dict[str, CELFunction] | None = ...
    ) -> Runner: ...

def json_to_cel(value: object) -> Any: ...
