from typing import Any

class CELEvalError(Exception): ...

class Runner:
    def evaluate(self, context: object) -> Any: ...

class Environment:
    def __init__(self) -> None: ...
    def compile(self, text: str) -> Any: ...
    def program(self, expr: Any) -> Runner: ...

def json_to_cel(value: object) -> Any: ...
