openapi: 3.0.2

info:
  title: {{ settings['service'].capitalize() }}
  description: >-
    Imbi is an operational management platform for medium to large environments.
  license:
    name: BSD 3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  version: {{ settings['version'] }}
  contact:
    name: the PSE Team
    url: https://github.com/aweber/imbi
  x-logo:
    url: /static/images/logo.png

server:
  url: {{ scheme }}://{{ host }}/

paths:
  /admin/configuration_system: {"$ref": "/schema/admin/configuration_system.yaml#/paths/create"}
  /admin/configuration_system/{configuration_system}: {"$ref": "/schema/admin/configuration_system.yaml#/paths/manage"}
  /admin/data_center: {"$ref": "/schema/admin/data_center.yaml#/paths/create"}
  /admin/data_center/{data_center}: {"$ref": "/schema/admin/data_center.yaml#/paths/manage"}
  /admin/cookie_cutter: {"$ref": "/schema/admin/cookie_cutter.yaml#/paths/create"}
  /admin/cookie_cutter/{cookie_cutter}: {"$ref": "/schema/admin/cookie_cutter.yaml#/paths/manage"}
  /admin/deployment_type: {"$ref": "/schema/admin/deployment_type.yaml#/paths/create"}
  /admin/deployment_type/{deployment_type}: {"$ref": "/schema/admin/deployment_type.yaml#/paths/manage"}
  /admin/environment: {"$ref": "/schema/admin/environment.yaml#/paths/create"}
  /admin/environment/{environment}: {"$ref": "/schema/admin/environment.yaml#/paths/manage"}
  /admin/group: {"$ref": "/schema/admin/group.yaml#/paths/create"}
  /admin/group/{name}: {"$ref": "/schema/admin/group.yaml#/paths/manage"}
  /admin/orchestration_system: {"$ref": "/schema/admin/orchestration_system.yaml#/paths/create"}
  /admin/orchestration_system/{orchestration_system}: {"$ref": "/schema/admin/orchestration_system.yaml#/paths/manage"}
  /admin/project_fact_type: {"$ref": "/schema/admin/project_fact_type.yaml#/paths/create"}
  /admin/project_fact_type/{id}: {"$ref": "/schema/admin/project_fact_type.yaml#/paths/manage"}
  /admin/project_link_type: {"$ref": "/schema/admin/project_link_type.yaml#/paths/create"}
  /admin/project_link_type/{link_type}: {"$ref": "/schema/admin/project_link_type.yaml#/paths/manage"}
  /admin/project_type: {"$ref": "/schema/admin/project_type.yaml#/paths/create"}
  /admin/project_type/{project_type}: {"$ref": "/schema/admin/project_type.yaml#/paths/manage"}
  /admin/team: {"$ref": "/schema/admin/team.yaml#/paths/create"}
  /admin/team/{id}: {"$ref": "/schema/admin/team.yaml#/paths/manage"}

  /project: {"$ref": "/schema/project/project.yaml#/paths/create"}
  /project/{id}: {"$ref": "/schema/project/project.yaml#/paths/manage"}
  /projects: {"$ref": "/schema/project/project.yaml#/paths/collection"}
  /project/{id}/dependency: {"$ref": "/schema/project/dependency.yaml#/paths/create"}
  /project/{id}/dependency/{project}: {"$ref": "/schema/project/dependency.yaml#/paths/manage"}
  /project/{id}/dependencies: {"$ref": "/schema/project/dependency.yaml#/paths/collection"}
  /project/{id}/link: {"$ref": "/schema/project/link.yaml#/paths/create"}
  /project/{id}/link/{link_type}: {"$ref": "/schema/project/link.yaml#/paths/manage"}
  /project/{id}/links: {"$ref": "/schema/project/link.yaml#/paths/collection"}
  /project/options: {"$ref": "/schema/project/options.yaml#/paths/options"}

  /settings/configuration_systems: {"$ref": "/schema/settings/configuration_systems.yaml#/paths/collection"}
  /settings/cookie_cutters: {"$ref": "/schema/settings/cookie_cutters.yaml#/paths/collection"}
  /settings/data_centers: {"$ref": "/schema/settings/data_centers.yaml#/paths/collection"}
  /settings/deployment_types: {"$ref": "/schema/settings/deployment_types.yaml#/paths/collection"}
  /settings/environments: {"$ref": "/schema/settings/environments.yaml#/paths/collection"}
  /settings/groups: {"$ref": "/schema/settings/groups.yaml#/paths/collection"}
  /settings/orchestration_systems: {"$ref": "/schema/settings/orchestration_systems.yaml#/paths/collection"}
  /settings/project_link_types: {"$ref": "/schema/settings/project_link_types.yaml#/paths/collection"}
  /settings/project_types: {"$ref": "/schema/settings/project_types.yaml#/paths/collection"}
  /settings/teams: {"$ref": "/schema/settings/teams.yaml#/paths/collection"}

  /status: {"$ref": "/schema/status.yaml#/paths/status"}

security:
  - api-key: []
  - session: []

components:
  securitySchemes:
    api-key:
      type: apiKey
      description: Uses an API key generated for a user to authenticate each API request
      in: header
      name: Private-Token
    session:
      type: apiKey
      description: Uses the session cookie of an authenticated user to authenticate each API request
      in: cookie
      name: session

tags:
  # - {"$ref": "/schema/admin/configuration_system.yaml#/tag"}
  - {"$ref": "/schema/admin/data_center.yaml#/tag"}
  - {"$ref": "/schema/admin/deployment_type.yaml#/tag"}
  - {"$ref": "/schema/admin/environment.yaml#/tag"}
  - {"$ref": "/schema/admin/group.yaml#/tag"}
  - {"$ref": "/schema/admin/orchestration_system.yaml#/tag"}
  - {"$ref": "/schema/admin/project_link_type.yaml#/tag"}
  - {"$ref": "/schema/admin/project_type.yaml#/tag"}
  - {"$ref": "/schema/admin/team.yaml#/tag"}
  - {"$ref": "/schema/project/project.yaml#/tag"}
  - {"$ref": "/schema/settings/common.yaml#/tag"}
  - {"$ref": "/schema/status.yaml#/tag"}

x-tagGroups:
  - name: Administration
    tags:
      - Configuration Systems
      - Data Centers
      - Deployment Types
      - Environments
      - Groups
      - Orchestration Systems
      - Project Fact Types
      - Project Link Types
      - Project Types
      - Teams
  - name: Other
    tags:
      - Health Check
  - name: Project Management
    tags:
      - Projects
  - name: Settings
    tags:
      - Settings
