name: Build and Deploy
on:
  push:
    tags: ["*"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'AWeber-Imbi/imbi'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: aweber/imbi
          tags: |
            type=semver,pattern={{tag}}
      - name: Setup API Environment
        run: sudo make deploy_setup
        shell: bash
      - name: Build
        run: make dist
      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: twine upload api/dist/imbi-${{ github.ref_name }}.tar.gz
        shell: bash
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to hub.docker.com
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./Dockerfile
          build-args: |
            VERSION=${{ steps.get_version.outputs.version }}
