name: Build and Deploy
on:
  push:
    branches-ignore: ["*"]
    tags: ["*"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && github.repository == 'aweber/imbi'
    steps:
      - name: Get the version
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup Environment
        run: sudo apt-get install -y python3 python3-pip python3-setuptools
      - name: Build
        run: make dist
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          skip_existing: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to hub.docker.com
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: aweber/imbi:${{ steps.get_version.outputs.version }}
          context: .
          file: ./Dockerfile
          build-args: |
            VERSION=${{ steps.get_version.outputs.version }}
      - name: Tag Latest
        run: |
          docker pull aweber/imbi:${{ steps.get_version.outputs.version }}
          docker tag aweber/imbi:${{ steps.get_version.outputs.version }}  aweber/imbi:latest
          docker push aweber/imbi:latest
