name: DDL Testing
on:
  push:
    branches: ["*"]
    paths:
      - "ddl/**"
    tags-ignore: ["*"]
  pull_request:
    branches: ["*"]
    paths:
      - "ddl/**"
  workflow_dispatch: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup Environment
        run: make ddl-setup
      - name: Run Tests
        run: make ddl-tests
