name: UI Testing
on:
  push:
    paths:
      - "ui/**"
    tags-ignore: ["*"]
  pull_request:
    paths:
      - "ui/**"
  workflow_dispatch: {}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup Environment
      run: make ui-setup
    - name: Run Tests
      run: make ui-tests
