export {default as Table} from "./Table"
export {default as Head} from "./Head"
export {default as Body} from "./Body"
export {default as Row} from "./Row"
export {default as Column} from "./Column"
export {default as Footer} from "./Footer"
